# Workflow All  - 4-stage Deep Learning Funnel

Notebook này điều khiển toàn bộ Phase 2 theo 4 stage, tối đa 35 training runs. Mỗi training cell chỉ chạy đúng một mô hình. Selector chỉ dùng validation metric; test metric chỉ dùng để báo cáo.

## Setup và helper functions

Chạy cell này trước. Notebook tự nhận khi chạy từ project root hoặc từ thư mục `Phần 2 mô hình`.

In [1]:
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import pandas as pd
import torch

PHASE2_DIR = Path.cwd()
if not (PHASE2_DIR / "train_gru.py").is_file():
    PHASE2_DIR = Path("Phần 2 mô hình").resolve()
if not (PHASE2_DIR / "train_gru.py").is_file():
    raise FileNotFoundError("Run this notebook from the project root or from 'Phần 2 mô hình'.")

sys.path.insert(0, str(PHASE2_DIR))

import train_gru
import train_attention_gru as train_attention
import train_multi_output_best_model as train_multi

GRU_RUNS_ROOT = PHASE2_DIR / "runs" / "gru_baseline"
ATTENTION_RUNS_ROOT = PHASE2_DIR / "runs" / "attention_gru"
MULTI_RUNS_ROOT = PHASE2_DIR / "runs" / "multi_output_best_model"
RUN_LOG: list[dict[str, object]] = []


def timed_train (stage: str, train_fn, config, **kwargs):
    start = time.perf_counter()
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    metrics = train_fn(config, **kwargs)
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    elapsed_minutes = (time.perf_counter() - start) / 60.0
    metrics["elapsed_minutes"] = elapsed_minutes
    run_dir = Path(str(metrics["run_dir"]))
    metrics_path = run_dir / "metrics.json"
    metrics_path.write_text(json.dumps(metrics, indent=2, ensure_ascii=False), encoding="utf-8")
    RUN_LOG.append({"stage": stage, "experiment_name": config.experiment_name, "elapsed_minutes": elapsed_minutes, "run_dir": str(run_dir)})
    print(f"{stage} | {config.experiment_name} | {elapsed_minutes:.2f} min")
    return metrics


def read_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def is_completed_run(run_dir: Path) -> bool:
    metrics_path = run_dir / "metrics.json"
    config_path = run_dir / "config.json"
    best_model_path = run_dir / "best_model.pt"
    if not metrics_path.is_file() or not config_path.is_file() or not best_model_path.is_file():
        return False
    metrics = read_json(metrics_path)
    config = read_json(config_path)
    name = str(config.get("experiment_name", run_dir.name)).lower()
    if "smoke" in name or "smoke" in run_dir.name.lower():
        return False
    if config.get("max_train_batches") is not None or config.get("max_eval_batches") is not None:
        return False
    return int(metrics.get("epochs_ran", 0)) > 1


def load_planned_status(stage_name: str, planned_runs: list[dict[str, object]], runs_root: Path, metric_columns: list[str]) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for item in planned_runs:
        run_dir = runs_root / str(item["experiment"])
        metrics_path = run_dir / "metrics.json"
        row = {"stage": stage_name, **item, "status": "pending", "run_dir": str(run_dir)}
        if metrics_path.is_file():
            metrics = read_json(metrics_path)
            row["status"] = "completed" if is_completed_run(run_dir) else "incomplete_or_smoke"
            for column in metric_columns:
                row[column] = metrics.get(column)
        rows.append(row)
    return pd.DataFrame(rows)


def rank_completed(status: pd.DataFrame, metric: str, loss_metric: str | None = None, top_k: int = 5) -> pd.DataFrame:
    completed = status[status["status"] == "completed"].copy()
    if completed.empty or metric not in completed.columns:
        return completed
    completed[metric] = pd.to_numeric(completed[metric], errors="coerce")
    completed = completed.dropna(subset=[metric])
    sort_cols = [metric]
    ascending = [False]
    if loss_metric is not None and loss_metric in completed.columns:
        completed[loss_metric] = pd.to_numeric(completed[loss_metric], errors="coerce")
        sort_cols.append(loss_metric)
        ascending.append(True)
    sort_cols.append("run")
    ascending.append(True)
    return completed.sort_values(sort_cols, ascending=ascending).head(top_k)


def select_top_configs(planned_runs: list[dict[str, object]], runs_root: Path, metric: str, loss_metric: str | None, top_k: int) -> tuple[list[dict[str, object]], pd.DataFrame]:
    status = load_planned_status("selection", planned_runs, runs_root, [metric, loss_metric or ""])
    ranking = rank_completed(status, metric, loss_metric, top_k)
    selected: list[dict[str, object]] = []
    for _, row in ranking.iterrows():
        run_dir = Path(str(row["run_dir"]))
        config = read_json(run_dir / "config.json")
        selected.append({"run": row["run"], "experiment": row["experiment"], "metric": row.get(metric), "config": config, "run_dir": str(run_dir)})
    return selected, ranking


def fallback_config(**values):
    return values


def pick_config(bank: list[dict[str, object]], index: int, fallback: dict[str, object]) -> dict[str, object]:
    if len(bank) > index:
        return dict(bank[index]["config"])
    return dict(fallback)


def apply_common(config, selected: dict[str, object], keys: list[str]) -> None:
    for key in keys:
        if hasattr(config, key) and key in selected:
            setattr(config, key, selected[key])


def show_status() -> pd.DataFrame:
    frames = [
        load_planned_status("Stage 1 GRU", GRU_PLANNED, GRU_RUNS_ROOT, ["best_val_macro_f1", "best_val_loss", "test_macro_f1", "test_accuracy", "elapsed_minutes", "epochs_ran"]),
        load_planned_status("Stage 2 Attention", ATTENTION_PLANNED, ATTENTION_RUNS_ROOT, ["best_val_macro_f1", "best_val_loss", "test_macro_f1", "test_accuracy", "elapsed_minutes", "epochs_ran"]),
        load_planned_status("Stage 3 Multi", MULTI_PLANNED, MULTI_RUNS_ROOT, ["best_val_composite_score", "val_cell_masked_macro_f1", "test_cell_masked_macro_f1", "test_pose_macro_f1", "elapsed_minutes", "epochs_ran"]),
        load_planned_status("Stage 4 Attention Final", FINAL_ATTENTION_PLANNED, ATTENTION_RUNS_ROOT, ["best_val_macro_f1", "best_val_loss", "test_macro_f1", "elapsed_minutes", "epochs_ran"]),
        load_planned_status("Stage 4 Multi Final", FINAL_MULTI_PLANNED, MULTI_RUNS_ROOT, ["best_val_composite_score", "val_cell_masked_macro_f1", "test_cell_masked_macro_f1", "elapsed_minutes", "epochs_ran"]),
    ]
    return pd.concat(frames, ignore_index=True)

C:\Users\nguyen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Planned experiment matrix

Tên run dùng prefix `S1_/S2_/S3_/S4_` để không lẫn với các run cũ. Không xóa thư mục `runs/`; dashboard chỉ đọc planned runs.

In [2]:
GRU_PLANNED = [
    {"run": "S1_G01", "experiment": "S1_G01_raw_h64", "profile": "raw", "hidden_size": 64, "num_layers": 1, "dropout": 0.0, "batch_size": 32, "lr": 1e-3, "purpose": "raw baseline đối chứng"},
    {"run": "S1_G02", "experiment": "S1_G02_raw_shift_h64_anchor", "profile": "raw_shift", "hidden_size": 64, "num_layers": 1, "dropout": 0.0, "batch_size": 32, "lr": 1e-3, "purpose": "anchor ổn định từ G02"},
    {"run": "S1_G03", "experiment": "S1_G03_raw_shift_h96", "profile": "raw_shift", "hidden_size": 96, "num_layers": 1, "dropout": 0.0, "batch_size": 32, "lr": 1e-3, "purpose": "capacity trung bình"},
    {"run": "S1_G04", "experiment": "S1_G04_raw_shift_h128", "profile": "raw_shift", "hidden_size": 128, "num_layers": 1, "dropout": 0.0, "batch_size": 32, "lr": 1e-3, "purpose": "capacity cao kiểm tra overfit"},
    {"run": "S1_G05", "experiment": "S1_G05_raw_shift_h64_l2_d03", "profile": "raw_shift", "hidden_size": 64, "num_layers": 2, "dropout": 0.3, "batch_size": 32, "lr": 1e-3, "purpose": "stacked GRU nhỏ"},
    {"run": "S1_G06", "experiment": "S1_G06_raw_shift_h96_l2_d03", "profile": "raw_shift", "hidden_size": 96, "num_layers": 2, "dropout": 0.3, "batch_size": 32, "lr": 1e-3, "purpose": "stacked GRU trung bình"},
    {"run": "S1_G07", "experiment": "S1_G07_raw_shift_h96_b64_lr0005", "profile": "raw_shift", "hidden_size": 96, "num_layers": 1, "dropout": 0.0, "batch_size": 64, "lr": 5e-4, "purpose": "batch/lr ổn định"},
]

ATTENTION_PLANNED = [
    {"run": "S2_A01", "experiment": "S2_A01_top_gru_a32", "profile": "selected", "hidden_size": "selected", "attention_dim": 32, "num_layers": "selected", "dropout": 0.2, "lr": "selected", "purpose": "top GRU -> attention a32"},
    {"run": "S2_A02", "experiment": "S2_A02_top_gru_a48", "profile": "selected", "hidden_size": "selected", "attention_dim": 48, "num_layers": "selected", "dropout": 0.2, "lr": "selected", "purpose": "top GRU -> attention a48"},
    {"run": "S2_A03", "experiment": "S2_A03_second_gru_a32", "profile": "selected", "hidden_size": "selected", "attention_dim": 32, "num_layers": "selected", "dropout": 0.2, "lr": "selected", "purpose": "second GRU branch"},
    {"run": "S2_A04", "experiment": "S2_A04_second_gru_l2_d03", "profile": "selected", "hidden_size": "selected", "attention_dim": 32, "num_layers": 2, "dropout": 0.3, "lr": "selected", "purpose": "stacked attention branch"},
    {"run": "S2_A05", "experiment": "S2_A05_raw_shift_h128_a32_d03", "profile": "raw_shift", "hidden_size": 128, "attention_dim": 32, "num_layers": 1, "dropout": 0.3, "lr": 1e-3, "purpose": "h128 regularized"},
    {"run": "S2_A06", "experiment": "S2_A06_raw_shift_h96_a64_d03", "profile": "raw_shift", "hidden_size": 96, "attention_dim": 64, "num_layers": 1, "dropout": 0.3, "lr": 1e-3, "purpose": "attention width upper"},
    {"run": "S2_A07", "experiment": "S2_A07_phase_hampel_shift_h96_a32", "profile": "phase_hampel_shift", "hidden_size": 96, "attention_dim": 32, "num_layers": 1, "dropout": 0.2, "lr": 1e-3, "purpose": "denoise+shift stability"},
    {"run": "S2_A08", "experiment": "S2_A08_phase_hampel_shift_noise_lr0005", "profile": "phase_hampel_shift", "hidden_size": 96, "attention_dim": 32, "num_layers": 1, "dropout": 0.3, "lr": 5e-4, "noise_sigma": 0.01, "purpose": "denoise+noise regularization"},
    {"run": "S2_A09", "experiment": "S2_A09_raw_shift_bigru_h64_a32", "profile": "raw_shift", "hidden_size": 64, "attention_dim": 32, "num_layers": 1, "dropout": 0.2, "lr": 1e-3, "bidirectional": True, "purpose": "BiGRU small probe"},
    {"run": "S2_A10", "experiment": "S2_A10_raw_shift_h96_a48_lr0005", "profile": "raw_shift", "hidden_size": 96, "attention_dim": 48, "num_layers": 1, "dropout": 0.3, "lr": 5e-4, "purpose": "A12-style regularized"},
]

MULTI_PLANNED = [
    {"run": "S3_M01", "experiment": "S3_M01_top_attention_linear", "profile": "selected", "cell_head_type": "linear", "cell_loss_type": "cross_entropy", "purpose": "multi baseline từ top attention"},
    {"run": "S3_M02", "experiment": "S3_M02_top_attention_mlp", "profile": "selected", "cell_head_type": "mlp", "cell_loss_type": "cross_entropy", "purpose": "MLP cell head"},
    {"run": "S3_M03", "experiment": "S3_M03_raw_shift_h128_mlp", "profile": "raw_shift", "cell_head_type": "mlp", "cell_loss_type": "cross_entropy", "purpose": "raw_shift h128 MLP"},
    {"run": "S3_M04", "experiment": "S3_M04_raw_shift_h128_mlp_cell2", "profile": "raw_shift", "cell_head_type": "mlp", "cell_loss_type": "cross_entropy", "loss_weight_cell": 2.0, "purpose": "cell loss x2"},
    {"run": "S3_M05", "experiment": "S3_M05_raw_shift_h128_mlp_focal", "profile": "raw_shift", "cell_head_type": "mlp", "cell_loss_type": "focal", "cell_focal_gamma": 2.0, "loss_weight_cell": 2.0, "purpose": "focal cell hard examples"},
    {"run": "S3_M06", "experiment": "S3_M06_raw_shift_h128_mlp_effective", "profile": "raw_shift", "cell_head_type": "mlp", "cell_loss_type": "focal", "cell_class_weighting": "effective_number", "cell_focal_gamma": 1.5, "loss_weight_cell": 2.0, "purpose": "effective-number class balance"},
    {"run": "S3_M07", "experiment": "S3_M07_phase_hampel_shift_mlp", "profile": "phase_hampel_shift", "cell_head_type": "mlp", "cell_loss_type": "cross_entropy", "purpose": "denoise multi baseline"},
    {"run": "S3_M08", "experiment": "S3_M08_phase_hampel_shift_mlp_noise", "profile": "phase_hampel_shift", "cell_head_type": "mlp", "cell_loss_type": "cross_entropy", "noise_sigma": 0.01, "dropout": 0.3, "purpose": "denoise+noise multi"},
    {"run": "S3_M09", "experiment": "S3_M09_raw_shift_mlp_l2_d03", "profile": "raw_shift", "cell_head_type": "mlp", "cell_loss_type": "cross_entropy", "num_layers": 2, "dropout": 0.3, "purpose": "stacked multi"},
    {"run": "S3_M10", "experiment": "S3_M10_raw_shift_bigru_mlp", "profile": "raw_shift", "cell_head_type": "mlp", "cell_loss_type": "cross_entropy", "bidirectional": True, "hidden_size": 64, "purpose": "BiGRU multi probe"},
]

FINAL_ATTENTION_PLANNED = [
    {"run": "S4_F01", "experiment": "S4_F01_attention_top_seed43", "profile": "selected", "purpose": "top attention seed check"},
    {"run": "S4_F02", "experiment": "S4_F02_attention_second_seed43", "profile": "selected", "purpose": "second attention seed check"},
]

FINAL_MULTI_PLANNED = [
    {"run": "S4_F03", "experiment": "S4_F03_multi_top_seed43", "profile": "selected", "purpose": "top multi seed 43"},
    {"run": "S4_F04", "experiment": "S4_F04_multi_top_seed44", "profile": "selected", "purpose": "top multi seed 44"},
    {"run": "S4_F05", "experiment": "S4_F05_multi_second_seed43", "profile": "selected", "purpose": "second multi seed 43"},
    {"run": "S4_F06", "experiment": "S4_F06_multi_linear_ablation", "profile": "selected", "purpose": "linear-vs-MLP ablation"},
    {"run": "S4_F07", "experiment": "S4_F07_multi_ce_ablation", "profile": "selected", "purpose": "CE-vs-focal ablation"},
    {"run": "S4_F08", "experiment": "S4_F08_multi_layer_ablation", "profile": "selected", "purpose": "num_layers ablation"},
]

ALL_PLANNED = (
    [{"stage": "Stage 1 GRU", **item} for item in GRU_PLANNED]
    + [{"stage": "Stage 2 Attention", **item} for item in ATTENTION_PLANNED]
    + [{"stage": "Stage 3 Multi", **item} for item in MULTI_PLANNED]
    + [{"stage": "Stage 4 Attention Final", **item} for item in FINAL_ATTENTION_PLANNED]
    + [{"stage": "Stage 4 Multi Final", **item} for item in FINAL_MULTI_PLANNED]
)

experiment_matrix = pd.DataFrame(ALL_PLANNED)
display(experiment_matrix)
print(f"Total planned training runs: {len(ALL_PLANNED)}")

,stage,run,experiment,profile,hidden_size,num_layers,dropout,batch_size,lr,purpose,attention_dim,noise_sigma,bidirectional,cell_head_type,cell_loss_type,loss_weight_cell,cell_focal_gamma,cell_class_weighting
0,Stage 1 GRU,S1_G01,S1_G01_raw_h64,raw,64,1,0.0,32.0,0.001,raw baseline đối chứng,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Stage 1 GRU,S1_G02,S1_G02_raw_shift_h64_anchor,raw_shift,64,1,0.0,32.0,0.001,anchor ổn định từ G02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Stage 1 GRU,S1_G03,S1_G03_raw_shift_h96,raw_shift,96,1,0.0,32.0,0.001,capacity trung bình,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Stage 1 GRU,S1_G04,S1_G04_raw_shift_h128,raw_shift,128,1,0.0,32.0,0.001,capacity cao kiểm tra overfit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Stage 1 GRU,S1_G05,S1_G05_raw_shift_h64_l2_d03,raw_shift,64,2,0.3,32.0,0.001,stacked GRU nhỏ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Stage 1 GRU,S1_G06,S1_G06_raw_shift_h96_l2_d03,raw_shift,96,2,0.3,32.0,0.001,stacked GRU trung bình,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Stage 1 GRU,S1_G07,S1_G07_raw_shift_h96_b64_lr0005,raw_shift,96,1,0.0,64.0,0.0005,batch/lr ổn định,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Stage 2 Attention,S2_A01,S2_A01_top_gru_a32,selected,selected,selected,0.2,NaN,selected,top GRU -> attention a32,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Stage 2 Attention,S2_A02,S2_A02_top_gru_a48,selected,selected,selected,0.2,NaN,selected,top GRU -> attention a48,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Stage 2 Attention,S2_A03,S2_A03_second_gru_a32,selected,selected,selected,0.2,NaN,selected,second GRU branch,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Stage 2 Attention,S2_A04,S2_A04_second_gru_l2_d03,selected,selected,2,0.3,NaN,selected,stacked attention branch,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Stage 2 Attention,S2_A05,S2_A05_raw_shift_h128_a32_d03,raw_shift,128,1,0.3,NaN,0.001,h128 regularized,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Stage 2 Attention,S2_A06,S2_A06_raw_shift_h96_a64_d03,raw_shift,96,1,0.3,NaN,0.001,attention width upper,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Stage 2 Attention,S2_A07,S2_A07_phase_hampel_shift_h96_a32,phase_hampel_shift,96,1,0.2,NaN,0.001,denoise+shift stability,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Stage 2 Attention,S2_A08,S2_A08_phase_hampel_shift_noise_lr0005,phase_hampel_shift,96,1,0.3,NaN,0.0005,denoise+noise regularization,32.0,0.01,NaN,NaN,NaN,NaN,NaN,NaN
15,Stage 2 Attention,S2_A09,S2_A09_raw_shift_bigru_h64_a32,raw_shift,64,1,0.2,NaN,0.001,BiGRU small probe,32.0,NaN,True,NaN,NaN,NaN,NaN,NaN
16,Stage 2 Attention,S2_A10,S2_A10_raw_shift_h96_a48_lr0005,raw_shift,96,1,0.3,NaN,0.0005,A12-style regularized,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Stage 3 Multi,S3_M01,S3_M01_top_attention_linear,selected,NaN,NaN,NaN,NaN,NaN,multi baseline từ top attention,NaN,NaN,NaN,linear,cross_entropy,NaN,NaN,NaN
18,Stage 3 Multi,S3_M02,S3_M02_top_attention_mlp,selected,NaN,NaN,NaN,NaN,NaN,MLP cell head,NaN,NaN,NaN,mlp,cross_entropy,NaN,NaN,NaN
19,Stage 3 Multi,S3_M03,S3_M03_raw_shift_h128_mlp,raw_shift,NaN,NaN,NaN,NaN,NaN,raw_shift h128 MLP,NaN,NaN,NaN,mlp,cross_entropy,NaN,NaN,NaN
20,Stage 3 Multi,S3_M04,S3_M04_raw_shift_h128_mlp_cell2,raw_shift,NaN,NaN,NaN,NaN,NaN,cell loss x2,NaN,NaN,NaN,mlp,cross_entropy,2.0,NaN,NaN
21,Stage 3 Multi,S3_M05,S3_M05_raw_shift_h128_mlp_focal,raw_shift,NaN,NaN,NaN,NaN,NaN,focal cell hard examples,NaN,NaN,NaN,mlp,focal,2.0,2.0,NaN
22,Stage 3 Multi,S3_M06,S3_M06_raw_shift_h128_mlp_effective,raw_shift,NaN,NaN,NaN,NaN,NaN,effective-number class balance,NaN,NaN,NaN,mlp,focal,2.0,1.5,effective_number
23,Stage 3 Multi,S3_M07,S3_M07_phase_hampel_shift_mlp,phase_hampel_shift,NaN,NaN,NaN,NaN,NaN,denoise multi baseline,NaN,NaN,NaN,mlp,cross_entropy,NaN,NaN,NaN
24,Stage 3 Multi,S3_M08,S3_M08_phase_hampel_shift_mlp_noise,phase_hampel_shift,NaN,NaN,0.3,NaN,NaN,denoise+noise multi,NaN,0.01,NaN,mlp,cross_entropy,NaN,NaN,NaN
25,Stage 3 Multi,S3_M09,S3_M09_raw_shift_mlp_l2_d03,raw_shift,NaN,2,0.3,NaN,NaN,stacked multi,NaN,NaN,NaN,mlp,cross_entropy,NaN,NaN,NaN
26,Stage 3 Multi,S3_M10,S3_M10_raw_shift_bigru_mlp,raw_shift,64,NaN,NaN,NaN,NaN,BiGRU multi probe,NaN,NaN,True,mlp,cross_entropy,NaN,NaN,NaN
27,Stage 4 Attention Final,S4_F01,S4_F01_attention_top_seed43,selected,NaN,NaN,NaN,NaN,NaN,top attention seed check,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Stage 4 Attention Final,S4_F02,S4_F02_attention_second_seed43,selected,NaN,NaN,NaN,NaN,NaN,second attention seed check,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Stage 4 Multi Final,S4_F03,S4_F03_multi_top_seed43,selected,NaN,NaN,NaN,NaN,NaN,top multi seed 43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Stage 4 Multi Final,S4_F04,S4_F04_multi_top_seed44,selected,NaN,NaN,NaN,NaN,NaN,top multi seed 44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Stage 4 Multi Final,S4_F05,S4_F05_multi_second_seed43,selected,NaN,NaN,NaN,NaN,NaN,second multi seed 43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Stage 4 Multi Final,S4_F06,S4_F06_multi_linear_ablation,selected,NaN,NaN,NaN,NaN,NaN,linear-vs-MLP ablation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Stage 4 Multi Final,S4_F07,S4_F07_multi_ce_ablation,selected,NaN,NaN,NaN,NaN,NaN,CE-vs-focal ablation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Stage 4 Multi Final,S4_F08,S4_F08_multi_layer_ablation,selected,NaN,NaN,NaN,NaN,NaN,num_layers ablation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Total planned training runs: 35

## Stage 1 - GRU baseline/capacity screening (`S1_G01`-`S1_G07`)

Mục tiêu: xác nhận anchor `raw_shift`, so sánh raw baseline, hidden size, batch/LR, và `num_layers=2`.

### S1_G01 - raw h64 baseline

In [3]:
config = train_gru.TrainConfig(experiment_name="S1_G01_raw_h64")
config.profile = "raw"
config.hidden_size = 64
config.num_layers = 1
config.dropout = 0.0
config.batch_size = 32
config.learning_rate = 0.001
config.bidirectional = False
timed_train("Stage 1 GRU", train_gru.train, config)

GRU baseline:  52%|█████▎    | 42/80 [00:10<00:09,  4.15it/s, val_f1=0.624, val_loss=0.934]

Stage 1 GRU | S1_G01_raw_h64 | 0.23 min

{'phase_name': 'GRU baseline',
 'profile': 'raw',
 'experiment_name': 'S1_G01_raw_h64',
 'hidden_size': 64,
 'dropout': 0.0,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 31,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 43,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\gru_baseline\\S1_G01_raw_h64',
 'best_val_accuracy': 0.7142857142857143,
 'best_val_macro_f1': 0.6500496671768794,
 'best_val_weighted_f1': 0.7151137727030707,
 'best_val_macro_precision': 0.6543400305858776,
 'best_val_macro_recall': 0.6522255178667212,
 'best_val_loss': 0.909488878931318,
 'test_accuracy': 0.6115107913669064,
 'test_macro_f1': 0.5636919673850591,
 'test_weighted_f1': 0.6215516956927217,
 'test_macro_precision': 0.5623720297344585,
 'test_macro_recall': 0.5820600358674775,
 'test_loss': 1.2032516645870621,
 'elapsed_minutes': 0.23240029666631018}

### S1_G02 - raw_shift h64 anchor

In [4]:
config = train_gru.TrainConfig(experiment_name="S1_G02_raw_shift_h64_anchor")
config.profile = "raw_shift"
config.hidden_size = 64
config.num_layers = 1
config.dropout = 0.0
config.batch_size = 32
config.learning_rate = 0.001
config.bidirectional = False
timed_train("Stage 1 GRU", train_gru.train, config)

GRU baseline:  44%|████▍     | 35/80 [00:33<00:43,  1.03it/s, val_f1=0.66, val_loss=1.61]

Stage 1 GRU | S1_G02_raw_shift_h64_anchor | 0.59 min

{'phase_name': 'GRU baseline',
 'profile': 'raw_shift',
 'experiment_name': 'S1_G02_raw_shift_h64_anchor',
 'hidden_size': 64,
 'dropout': 0.0,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 24,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 36,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\gru_baseline\\S1_G02_raw_shift_h64_anchor',
 'best_val_accuracy': 0.7571428571428571,
 'best_val_macro_f1': 0.694430085958393,
 'best_val_weighted_f1': 0.7563742329608623,
 'best_val_macro_precision': 0.7162799189114979,
 'best_val_macro_recall': 0.6937977318587009,
 'best_val_loss': 1.2457377399717058,
 'test_accuracy': 0.7338129496402878,
 'test_macro_f1': 0.6876813841098146,
 'test_weighted_f1': 0.7349378754496386,
 'test_macro_precision': 0.699577565291851,
 'test_macro_recall': 0.6847184459427673,
 'test_loss': 1.4165153829313868,
 'elapsed_minutes': 0.5933822699997109}

### S1_G03 - raw_shift h96

In [5]:
config = train_gru.TrainConfig(experiment_name="S1_G03_raw_shift_h96")
config.profile = "raw_shift"
config.hidden_size = 96
config.num_layers = 1
config.dropout = 0.0
config.batch_size = 32
config.learning_rate = 0.001
config.bidirectional = False
timed_train("Stage 1 GRU", train_gru.train, config)

GRU baseline:  29%|██▉       | 23/80 [00:23<00:59,  1.04s/it, val_f1=0.633, val_loss=1.52]

Stage 1 GRU | S1_G03_raw_shift_h96 | 0.43 min

{'phase_name': 'GRU baseline',
 'profile': 'raw_shift',
 'experiment_name': 'S1_G03_raw_shift_h96',
 'hidden_size': 96,
 'dropout': 0.0,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 12,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 24,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\gru_baseline\\S1_G03_raw_shift_h96',
 'best_val_accuracy': 0.7214285714285714,
 'best_val_macro_f1': 0.6695361963513368,
 'best_val_weighted_f1': 0.7203889202278797,
 'best_val_macro_precision': 0.6595458582546101,
 'best_val_macro_recall': 0.6964924267579372,
 'best_val_loss': 1.007115295955113,
 'test_accuracy': 0.6762589928057554,
 'test_macro_f1': 0.6111958873590663,
 'test_weighted_f1': 0.6783597242431304,
 'test_macro_precision': 0.6096153081115487,
 'test_macro_recall': 0.6283276765951463,
 'test_loss': 1.2017238783321793,
 'elapsed_minutes': 0.42739277333312203}

### S1_G04 - raw_shift h128

In [6]:
config = train_gru.TrainConfig(experiment_name="S1_G04_raw_shift_h128")
config.profile = "raw_shift"
config.hidden_size = 128
config.num_layers = 1
config.dropout = 0.0
config.batch_size = 32
config.learning_rate = 0.001
config.bidirectional = False
timed_train("Stage 1 GRU", train_gru.train, config)

GRU baseline:  60%|██████    | 48/80 [00:47<00:31,  1.00it/s, val_f1=0.704, val_loss=1.93]

Stage 1 GRU | S1_G04_raw_shift_h128 | 0.82 min

{'phase_name': 'GRU baseline',
 'profile': 'raw_shift',
 'experiment_name': 'S1_G04_raw_shift_h128',
 'hidden_size': 128,
 'dropout': 0.0,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 37,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 49,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\gru_baseline\\S1_G04_raw_shift_h128',
 'best_val_accuracy': 0.8071428571428572,
 'best_val_macro_f1': 0.7474483086826386,
 'best_val_weighted_f1': 0.8018652674872541,
 'best_val_macro_precision': 0.7598928370480095,
 'best_val_macro_recall': 0.7442929299379326,
 'best_val_loss': 1.8148978224822454,
 'test_accuracy': 0.7194244604316546,
 'test_macro_f1': 0.6551289817639836,
 'test_weighted_f1': 0.7179465900159934,
 'test_macro_precision': 0.6681166219611283,
 'test_macro_recall': 0.6573911874959644,
 'test_loss': 2.284925652922486,
 'elapsed_minutes': 0.8241323250006342}

### S1_G05 - raw_shift h64 num_layers2 dropout03

In [7]:
config = train_gru.TrainConfig(experiment_name="S1_G05_raw_shift_h64_l2_d03")
config.profile = "raw_shift"
config.hidden_size = 64
config.num_layers = 2
config.dropout = 0.3
config.batch_size = 32
config.learning_rate = 0.001
config.bidirectional = False
timed_train("Stage 1 GRU", train_gru.train, config)

GRU baseline:  57%|█████▊    | 46/80 [00:42<00:31,  1.09it/s, val_f1=0.703, val_loss=2.04]

Stage 1 GRU | S1_G05_raw_shift_h64_l2_d03 | 0.73 min

{'phase_name': 'GRU baseline',
 'profile': 'raw_shift',
 'experiment_name': 'S1_G05_raw_shift_h64_l2_d03',
 'hidden_size': 64,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'num_layers': 2,
 'bidirectional': False,
 'best_epoch': 35,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 47,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\gru_baseline\\S1_G05_raw_shift_h64_l2_d03',
 'best_val_accuracy': 0.7714285714285715,
 'best_val_macro_f1': 0.7217172499498333,
 'best_val_weighted_f1': 0.7638925306192857,
 'best_val_macro_precision': 0.7700175764085538,
 'best_val_macro_recall': 0.7061768856478762,
 'best_val_loss': 1.8065530572618758,
 'test_accuracy': 0.7050359712230215,
 'test_macro_f1': 0.6593515033589548,
 'test_weighted_f1': 0.7028508039895499,
 'test_macro_precision': 0.6837650444793303,
 'test_macro_recall': 0.6526767185458713,
 'test_loss': 2.36928478505114,
 'elapsed_minutes': 0.730706961666389}

### S1_G06 - raw_shift h96 num_layers2 dropout03

In [8]:
config = train_gru.TrainConfig(experiment_name="S1_G06_raw_shift_h96_l2_d03")
config.profile = "raw_shift"
config.hidden_size = 96
config.num_layers = 2
config.dropout = 0.3
config.batch_size = 32
config.learning_rate = 0.001
config.bidirectional = False
timed_train("Stage 1 GRU", train_gru.train, config)

GRU baseline:  35%|███▌      | 28/80 [00:27<00:51,  1.00it/s, val_f1=0.725, val_loss=1.61]

Stage 1 GRU | S1_G06_raw_shift_h96_l2_d03 | 0.49 min

{'phase_name': 'GRU baseline',
 'profile': 'raw_shift',
 'experiment_name': 'S1_G06_raw_shift_h96_l2_d03',
 'hidden_size': 96,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'num_layers': 2,
 'bidirectional': False,
 'best_epoch': 17,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 29,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\gru_baseline\\S1_G06_raw_shift_h96_l2_d03',
 'best_val_accuracy': 0.8071428571428572,
 'best_val_macro_f1': 0.7435100846865552,
 'best_val_weighted_f1': 0.8001213165919049,
 'best_val_macro_precision': 0.7585386835386835,
 'best_val_macro_recall': 0.7365273236954356,
 'best_val_loss': 1.3434253249849593,
 'test_accuracy': 0.7194244604316546,
 'test_macro_f1': 0.6592607010498235,
 'test_weighted_f1': 0.7172792909792959,
 'test_macro_precision': 0.6928023797096746,
 'test_macro_recall': 0.6661077621971937,
 'test_loss': 1.577546914704412,
 'elapsed_minutes': 0.49158248833361234}

### S1_G07 - raw_shift h96 batch64 lr0005

In [9]:
config = train_gru.TrainConfig(experiment_name="S1_G07_raw_shift_h96_b64_lr0005")
config.profile = "raw_shift"
config.hidden_size = 96
config.num_layers = 1
config.dropout = 0.0
config.batch_size = 64
config.learning_rate = 0.0005
config.bidirectional = False
timed_train("Stage 1 GRU", train_gru.train, config)

GRU baseline:  38%|███▊      | 30/80 [00:22<00:38,  1.31it/s, val_f1=0.65, val_loss=1.12]

Stage 1 GRU | S1_G07_raw_shift_h96_b64_lr0005 | 0.41 min

{'phase_name': 'GRU baseline',
 'profile': 'raw_shift',
 'experiment_name': 'S1_G07_raw_shift_h96_b64_lr0005',
 'hidden_size': 96,
 'dropout': 0.0,
 'batch_size': 64,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 19,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 31,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\gru_baseline\\S1_G07_raw_shift_h96_b64_lr0005',
 'best_val_accuracy': 0.7357142857142858,
 'best_val_macro_f1': 0.7007770449610343,
 'best_val_weighted_f1': 0.7393693563795288,
 'best_val_macro_precision': 0.6871477553626474,
 'best_val_macro_recall': 0.7336314845086971,
 'best_val_loss': 0.914740766797747,
 'test_accuracy': 0.6330935251798561,
 'test_macro_f1': 0.581302056438717,
 'test_weighted_f1': 0.6461628153190414,
 'test_macro_precision': 0.5914393125671321,
 'test_macro_recall': 0.6035177447107155,
 'test_loss': 1.2286402480207759,
 'elapsed_minutes': 0.4068694500000371}

## Stage 1 selection

Chọn top 3 GRU theo `best_val_macro_f1`, tie-break bằng `best_val_loss`.

In [10]:
gru_status = load_planned_status("Stage 1 GRU", GRU_PLANNED, GRU_RUNS_ROOT, ["best_val_macro_f1", "best_val_loss", "test_macro_f1", "test_accuracy", "elapsed_minutes", "epochs_ran"])
display(gru_status)
top_gru_configs, top_gru_ranking = select_top_configs(GRU_PLANNED, GRU_RUNS_ROOT, "best_val_macro_f1", "best_val_loss", 3)
display(top_gru_ranking)

,stage,run,experiment,profile,hidden_size,num_layers,dropout,batch_size,lr,purpose,status,run_dir,best_val_macro_f1,best_val_loss,test_macro_f1,test_accuracy,elapsed_minutes,epochs_ran
0,Stage 1 GRU,S1_G01,S1_G01_raw_h64,raw,64,1,0.0,32,0.0010,raw baseline đối chứng,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.650050,0.909489,0.563692,0.611511,0.232400,43
1,Stage 1 GRU,S1_G02,S1_G02_raw_shift_h64_anchor,raw_shift,64,1,0.0,32,0.0010,anchor ổn định từ G02,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.694430,1.245738,0.687681,0.733813,0.593382,36
2,Stage 1 GRU,S1_G03,S1_G03_raw_shift_h96,raw_shift,96,1,0.0,32,0.0010,capacity trung bình,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.669536,1.007115,0.611196,0.676259,0.427393,24
3,Stage 1 GRU,S1_G04,S1_G04_raw_shift_h128,raw_shift,128,1,0.0,32,0.0010,capacity cao kiểm tra overfit,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.747448,1.814898,0.655129,0.719424,0.824132,49
4,Stage 1 GRU,S1_G05,S1_G05_raw_shift_h64_l2_d03,raw_shift,64,2,0.3,32,0.0010,stacked GRU nhỏ,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.721717,1.806553,0.659352,0.705036,0.730707,47
5,Stage 1 GRU,S1_G06,S1_G06_raw_shift_h96_l2_d03,raw_shift,96,2,0.3,32,0.0010,stacked GRU trung bình,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.743510,1.343425,0.659261,0.719424,0.491582,29
6,Stage 1 GRU,S1_G07,S1_G07_raw_shift_h96_b64_lr0005,raw_shift,96,1,0.0,64,0.0005,batch/lr ổn định,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.700777,0.914741,0.581302,0.633094,0.406869,31

,stage,run,experiment,profile,hidden_size,num_layers,dropout,batch_size,lr,purpose,status,run_dir,best_val_macro_f1,best_val_loss
3,selection,S1_G04,S1_G04_raw_shift_h128,raw_shift,128,1,0.0,32,0.001,capacity cao kiểm tra overfit,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.747448,1.814898
5,selection,S1_G06,S1_G06_raw_shift_h96_l2_d03,raw_shift,96,2,0.3,32,0.001,stacked GRU trung bình,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.743510,1.343425
4,selection,S1_G05,S1_G05_raw_shift_h64_l2_d03,raw_shift,64,2,0.3,32,0.001,stacked GRU nhỏ,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.721717,1.806553

## Stage 2 - Attention-GRU narrowing (`S2_A01`-`S2_A10`)

Mục tiêu: dùng top GRU làm backbone bank, sau đó thử attention dim, dropout, denoise branch, noise nhẹ và BiGRU nhỏ.

### S2_A01 - top GRU attention a32

In [11]:
selected = pick_config(top_gru_configs, 0, fallback_config(profile='raw_shift', hidden_size=96, batch_size=32, learning_rate=0.001, weight_decay=0.0001, num_layers=1, dropout=0.0, bidirectional=False))
config = train_attention.TrainConfig(experiment_name="S2_A01_top_gru_a32")
apply_common(config, selected, ["profile", "hidden_size", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "bidirectional"])
config.attention_dim = 32
config.dropout = 0.2


config.noise_sigma = 0.0
config.bidirectional = False or config.bidirectional
timed_train("Stage 2 Attention", train_attention.train, config)

Attention-GRU:  33%|███▎      | 33/100 [00:33<01:07,  1.00s/it, val_f1=0.699, val_loss=1.79]

Stage 2 Attention | S2_A01_top_gru_a32 | 0.58 min

{'phase_name': 'Attention-GRU',
 'profile': 'raw_shift',
 'experiment_name': 'S2_A01_top_gru_a32',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.2,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 19,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 34,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S2_A01_top_gru_a32',
 'best_val_accuracy': 0.7714285714285715,
 'best_val_macro_f1': 0.724154080288172,
 'best_val_weighted_f1': 0.7734564948879641,
 'best_val_macro_precision': 0.7418883382699172,
 'best_val_macro_recall': 0.7213297553063779,
 'best_val_loss': 1.542205079964229,
 'test_accuracy': 0.6618705035971223,
 'test_macro_f1': 0.5874128987733476,
 'test_weighted_f1': 0.6537015548851242,
 'test_macro_precision': 0.6119960984717546,
 'test_macro_recall': 0.5930423631314647,
 'test_loss': 2.0532512767709417,
 'elapsed_minutes': 0.5775039149991547}

### S2_A02 - top GRU attention a48

In [12]:
selected = pick_config(top_gru_configs, 0, fallback_config(profile='raw_shift', hidden_size=96, batch_size=32, learning_rate=0.001, weight_decay=0.0001, num_layers=1, dropout=0.0, bidirectional=False))
config = train_attention.TrainConfig(experiment_name="S2_A02_top_gru_a48")
apply_common(config, selected, ["profile", "hidden_size", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "bidirectional"])
config.attention_dim = 48
config.dropout = 0.2


config.noise_sigma = 0.0
config.bidirectional = False or config.bidirectional
timed_train("Stage 2 Attention", train_attention.train, config)

Attention-GRU:  36%|███▌      | 36/100 [00:35<01:03,  1.01it/s, val_f1=0.647, val_loss=2.07]

Stage 2 Attention | S2_A02_top_gru_a48 | 0.62 min

{'phase_name': 'Attention-GRU',
 'profile': 'raw_shift',
 'experiment_name': 'S2_A02_top_gru_a48',
 'hidden_size': 128,
 'attention_dim': 48,
 'dropout': 0.2,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 22,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 37,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S2_A02_top_gru_a48',
 'best_val_accuracy': 0.7571428571428571,
 'best_val_macro_f1': 0.6919557363388052,
 'best_val_weighted_f1': 0.7540689308943048,
 'best_val_macro_precision': 0.699389870890885,
 'best_val_macro_recall': 0.6970232241832903,
 'best_val_loss': 1.4964902222156524,
 'test_accuracy': 0.6762589928057554,
 'test_macro_f1': 0.6246969196217317,
 'test_weighted_f1': 0.6769996852825327,
 'test_macro_precision': 0.6247957424728133,
 'test_macro_recall': 0.6292590111169437,
 'test_loss': 2.009026150051638,
 'elapsed_minutes': 0.6228333716659108}

### S2_A03 - second GRU attention a32

In [13]:
selected = pick_config(top_gru_configs, 1, fallback_config(profile='raw_shift', hidden_size=96, batch_size=32, learning_rate=0.001, weight_decay=0.0001, num_layers=1, dropout=0.0, bidirectional=False))
config = train_attention.TrainConfig(experiment_name="S2_A03_second_gru_a32")
apply_common(config, selected, ["profile", "hidden_size", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "bidirectional"])
config.attention_dim = 32
config.dropout = 0.2


config.noise_sigma = 0.0
config.bidirectional = False or config.bidirectional
timed_train("Stage 2 Attention", train_attention.train, config)

Attention-GRU:  35%|███▌      | 35/100 [00:34<01:03,  1.02it/s, val_f1=0.698, val_loss=1.95]

Stage 2 Attention | S2_A03_second_gru_a32 | 0.60 min

{'phase_name': 'Attention-GRU',
 'profile': 'raw_shift',
 'experiment_name': 'S2_A03_second_gru_a32',
 'hidden_size': 96,
 'attention_dim': 32,
 'dropout': 0.2,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 2,
 'bidirectional': False,
 'best_epoch': 21,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 36,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S2_A03_second_gru_a32',
 'best_val_accuracy': 0.7642857142857142,
 'best_val_macro_f1': 0.7087609052945189,
 'best_val_weighted_f1': 0.758510546409706,
 'best_val_macro_precision': 0.7261613386613386,
 'best_val_macro_recall': 0.701487509897576,
 'best_val_loss': 1.5349908896854945,
 'test_accuracy': 0.7050359712230215,
 'test_macro_f1': 0.6403426614590116,
 'test_weighted_f1': 0.7069701821548515,
 'test_macro_precision': 0.6348072562358277,
 'test_macro_recall': 0.6480369441263757,
 'test_loss': 1.939577421696066,
 'elapsed_minutes': 0.5989359583337015}

### S2_A04 - second GRU stacked attention

In [14]:
selected = pick_config(top_gru_configs, 1, fallback_config(profile='raw_shift', hidden_size=96, batch_size=32, learning_rate=0.001, weight_decay=0.0001, num_layers=1, dropout=0.0, bidirectional=False))
config = train_attention.TrainConfig(experiment_name="S2_A04_second_gru_l2_d03")
apply_common(config, selected, ["profile", "hidden_size", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "bidirectional"])
config.attention_dim = 32
config.dropout = 0.3
config.num_layers = 2

config.noise_sigma = 0.0
config.bidirectional = False or config.bidirectional
timed_train("Stage 2 Attention", train_attention.train, config)

Attention-GRU:  31%|███       | 31/100 [00:30<01:08,  1.01it/s, val_f1=0.708, val_loss=1.68]

Stage 2 Attention | S2_A04_second_gru_l2_d03 | 0.54 min

{'phase_name': 'Attention-GRU',
 'profile': 'raw_shift',
 'experiment_name': 'S2_A04_second_gru_l2_d03',
 'hidden_size': 96,
 'attention_dim': 32,
 'dropout': 0.3,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 2,
 'bidirectional': False,
 'best_epoch': 17,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 32,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S2_A04_second_gru_l2_d03',
 'best_val_accuracy': 0.7642857142857142,
 'best_val_macro_f1': 0.7187937195080052,
 'best_val_weighted_f1': 0.7673210334638907,
 'best_val_macro_precision': 0.7281403345082591,
 'best_val_macro_recall': 0.7172821256162039,
 'best_val_loss': 1.310521913426263,
 'test_accuracy': 0.6906474820143885,
 'test_macro_f1': 0.6415332290735084,
 'test_weighted_f1': 0.688188474782552,
 'test_macro_precision': 0.6845571561958117,
 'test_macro_recall': 0.6267911199435001,
 'test_loss': 1.658483633034521,
 'elapsed_minutes': 0.5375154083332745}

### S2_A05 - raw_shift h128 a32 dropout03

In [15]:
selected = fallback_config(profile='raw_shift', hidden_size=128, batch_size=32, learning_rate=0.001, weight_decay=0.0001, num_layers=1, dropout=0.3, bidirectional=False)
config = train_attention.TrainConfig(experiment_name="S2_A05_raw_shift_h128_a32_d03")
apply_common(config, selected, ["profile", "hidden_size", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "bidirectional"])
config.attention_dim = 32
config.dropout = 0.3


config.noise_sigma = 0.0
config.bidirectional = False or config.bidirectional
timed_train("Stage 2 Attention", train_attention.train, config)

Attention-GRU:  34%|███▍      | 34/100 [00:34<01:07,  1.02s/it, val_f1=0.668, val_loss=2.03]

Stage 2 Attention | S2_A05_raw_shift_h128_a32_d03 | 0.61 min

{'phase_name': 'Attention-GRU',
 'profile': 'raw_shift',
 'experiment_name': 'S2_A05_raw_shift_h128_a32_d03',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 20,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 35,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S2_A05_raw_shift_h128_a32_d03',
 'best_val_accuracy': 0.7571428571428571,
 'best_val_macro_f1': 0.7100855120822464,
 'best_val_weighted_f1': 0.7568829028347247,
 'best_val_macro_precision': 0.7530416077774004,
 'best_val_macro_recall': 0.6866331639038593,
 'best_val_loss': 1.4498113802501134,
 'test_accuracy': 0.6330935251798561,
 'test_macro_f1': 0.5744179290097657,
 'test_weighted_f1': 0.6399807797546748,
 'test_macro_precision': 0.5971778221778222,
 'test_macro_recall': 0.5675954349805516,
 'test_loss': 2.177431287525369,
 'elapsed_minutes': 0.607336508333295}

### S2_A06 - raw_shift h96 a64 dropout03

In [16]:
selected = fallback_config(profile='raw_shift', hidden_size=96, batch_size=32, learning_rate=0.001, weight_decay=0.0001, num_layers=1, dropout=0.3, bidirectional=False)
config = train_attention.TrainConfig(experiment_name="S2_A06_raw_shift_h96_a64_d03")
apply_common(config, selected, ["profile", "hidden_size", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "bidirectional"])
config.attention_dim = 64
config.dropout = 0.3


config.noise_sigma = 0.0
config.bidirectional = False or config.bidirectional
timed_train("Stage 2 Attention", train_attention.train, config)

Attention-GRU:  39%|███▉      | 39/100 [00:38<00:59,  1.02it/s, val_f1=0.625, val_loss=2.41]

Stage 2 Attention | S2_A06_raw_shift_h96_a64_d03 | 0.66 min

{'phase_name': 'Attention-GRU',
 'profile': 'raw_shift',
 'experiment_name': 'S2_A06_raw_shift_h96_a64_d03',
 'hidden_size': 96,
 'attention_dim': 64,
 'dropout': 0.3,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 25,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 40,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S2_A06_raw_shift_h96_a64_d03',
 'best_val_accuracy': 0.7714285714285715,
 'best_val_macro_f1': 0.7031875267974221,
 'best_val_weighted_f1': 0.774120276948618,
 'best_val_macro_precision': 0.7503170771027914,
 'best_val_macro_recall': 0.6863713570534598,
 'best_val_loss': 1.5271647231919425,
 'test_accuracy': 0.6402877697841727,
 'test_macro_f1': 0.5733890936906729,
 'test_weighted_f1': 0.643306722488417,
 'test_macro_precision': 0.5809523809523809,
 'test_macro_recall': 0.576637822388998,
 'test_loss': 2.4095903352010164,
 'elapsed_minutes': 0.663559481666501}

### S2_A07 - phase_hampel_shift h96 a32

In [17]:
selected = fallback_config(profile='phase_hampel_shift', hidden_size=96, batch_size=32, learning_rate=0.001, weight_decay=0.0001, num_layers=1, dropout=0.2, bidirectional=False)
config = train_attention.TrainConfig(experiment_name="S2_A07_phase_hampel_shift_h96_a32")
apply_common(config, selected, ["profile", "hidden_size", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "bidirectional"])
config.attention_dim = 32
config.dropout = 0.2


config.noise_sigma = 0.0
config.bidirectional = False or config.bidirectional
timed_train("Stage 2 Attention", train_attention.train, config)

Attention-GRU:  30%|███       | 30/100 [00:30<01:10,  1.01s/it, val_f1=0.607, val_loss=2.2]

Stage 2 Attention | S2_A07_phase_hampel_shift_h96_a32 | 0.53 min

{'phase_name': 'Attention-GRU',
 'profile': 'phase_hampel_shift',
 'experiment_name': 'S2_A07_phase_hampel_shift_h96_a32',
 'hidden_size': 96,
 'attention_dim': 32,
 'dropout': 0.2,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 16,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 31,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S2_A07_phase_hampel_shift_h96_a32',
 'best_val_accuracy': 0.7357142857142858,
 'best_val_macro_f1': 0.6589033715190197,
 'best_val_weighted_f1': 0.7291288054226375,
 'best_val_macro_precision': 0.7011505919891013,
 'best_val_macro_recall': 0.6475034162601211,
 'best_val_loss': 1.5809775467429843,
 'test_accuracy': 0.6906474820143885,
 'test_macro_f1': 0.6494030417339871,
 'test_weighted_f1': 0.6943804982215199,
 'test_macro_precision': 0.6772394272394272,
 'test_macro_recall': 0.6714864785774777,
 'test_loss': 1.6270752004582247,
 'elapsed_minutes': 0.5311542983331795}

### S2_A08 - phase_hampel_shift noise lr0005

In [18]:
selected = fallback_config(profile='phase_hampel_shift', hidden_size=96, batch_size=32, learning_rate=0.0005, weight_decay=0.0001, num_layers=1, dropout=0.3, bidirectional=False)
config = train_attention.TrainConfig(experiment_name="S2_A08_phase_hampel_shift_noise_lr0005")
apply_common(config, selected, ["profile", "hidden_size", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "bidirectional"])
config.attention_dim = 32
config.dropout = 0.3

config.learning_rate = 0.0005
config.noise_sigma = 0.01
config.bidirectional = False or config.bidirectional
timed_train("Stage 2 Attention", train_attention.train, config)

Attention-GRU:  34%|███▍      | 34/100 [02:04<04:02,  3.67s/it, val_f1=0.602, val_loss=2.12]

Stage 2 Attention | S2_A08_phase_hampel_shift_noise_lr0005 | 2.11 min

{'phase_name': 'Attention-GRU',
 'profile': 'phase_hampel_shift',
 'experiment_name': 'S2_A08_phase_hampel_shift_noise_lr0005',
 'hidden_size': 96,
 'attention_dim': 32,
 'dropout': 0.3,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.01,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 20,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 35,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S2_A08_phase_hampel_shift_noise_lr0005',
 'best_val_accuracy': 0.7285714285714285,
 'best_val_macro_f1': 0.6505605416769883,
 'best_val_weighted_f1': 0.7277201674320521,
 'best_val_macro_precision': 0.6623629208768528,
 'best_val_macro_recall': 0.6448398508339507,
 'best_val_loss': 1.3022922890526907,
 'test_accuracy': 0.6187050359712231,
 'test_macro_f1': 0.534851041057422,
 'test_weighted_f1': 0.6270765927221023,
 'test_macro_precision': 0.5431901431901431,
 'test_macro_recall': 0.5446034813393117,
 'test_loss': 1.6742596737772442,
 'elapsed_minutes': 2.1061730066663586}

### S2_A09 - raw_shift BiGRU h64 a32

In [19]:
selected = fallback_config(profile='raw_shift', hidden_size=64, batch_size=32, learning_rate=0.001, weight_decay=0.0001, num_layers=1, dropout=0.2, bidirectional=True)
config = train_attention.TrainConfig(experiment_name="S2_A09_raw_shift_bigru_h64_a32")
apply_common(config, selected, ["profile", "hidden_size", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "bidirectional"])
config.attention_dim = 32
config.dropout = 0.2


config.noise_sigma = 0.0
config.bidirectional = True or config.bidirectional
timed_train("Stage 2 Attention", train_attention.train, config)

Attention-GRU:  20%|██        | 20/100 [00:28<01:53,  1.42s/it, val_f1=0.684, val_loss=1.24]

Stage 2 Attention | S2_A09_raw_shift_bigru_h64_a32 | 0.50 min

{'phase_name': 'Attention-GRU',
 'profile': 'raw_shift',
 'experiment_name': 'S2_A09_raw_shift_bigru_h64_a32',
 'hidden_size': 64,
 'attention_dim': 32,
 'dropout': 0.2,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': True,
 'best_epoch': 6,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 21,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S2_A09_raw_shift_bigru_h64_a32',
 'best_val_accuracy': 0.7357142857142858,
 'best_val_macro_f1': 0.7035038882259392,
 'best_val_weighted_f1': 0.7365086145075052,
 'best_val_macro_precision': 0.6928639192023948,
 'best_val_macro_recall': 0.7305568503997344,
 'best_val_loss': 0.8724282435008458,
 'test_accuracy': 0.6115107913669064,
 'test_macro_f1': 0.5770289184562885,
 'test_weighted_f1': 0.6266428527030811,
 'test_macro_precision': 0.5793650793650793,
 'test_macro_recall': 0.6163156653318357,
 'test_loss': 1.031600962439887,
 'elapsed_minutes': 0.5021076733333757}

### S2_A10 - raw_shift h96 a48 lr0005

In [20]:
selected = fallback_config(profile='raw_shift', hidden_size=96, batch_size=32, learning_rate=0.0005, weight_decay=0.0001, num_layers=1, dropout=0.3, bidirectional=False)
config = train_attention.TrainConfig(experiment_name="S2_A10_raw_shift_h96_a48_lr0005")
apply_common(config, selected, ["profile", "hidden_size", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "bidirectional"])
config.attention_dim = 48
config.dropout = 0.3

config.learning_rate = 0.0005
config.noise_sigma = 0.0
config.bidirectional = False or config.bidirectional
timed_train("Stage 2 Attention", train_attention.train, config)

Attention-GRU:  39%|███▉      | 39/100 [00:52<01:21,  1.34s/it, val_f1=0.661, val_loss=1.63]

Stage 2 Attention | S2_A10_raw_shift_h96_a48_lr0005 | 0.90 min

{'phase_name': 'Attention-GRU',
 'profile': 'raw_shift',
 'experiment_name': 'S2_A10_raw_shift_h96_a48_lr0005',
 'hidden_size': 96,
 'attention_dim': 48,
 'dropout': 0.3,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 25,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 40,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S2_A10_raw_shift_h96_a48_lr0005',
 'best_val_accuracy': 0.7428571428571429,
 'best_val_macro_f1': 0.7103023846587375,
 'best_val_weighted_f1': 0.7464292776161909,
 'best_val_macro_precision': 0.7426152463888313,
 'best_val_macro_recall': 0.7130796467523179,
 'best_val_loss': 1.1018740854093008,
 'test_accuracy': 0.7050359712230215,
 'test_macro_f1': 0.6741193306658203,
 'test_weighted_f1': 0.7055210791713052,
 'test_macro_precision': 0.6963737659681961,
 'test_macro_recall': 0.6767603304852707,
 'test_loss': 1.5312501826732279,
 'elapsed_minutes': 0.9024885383337581}

## Stage 2 selection

Chọn top 4 Attention-GRU theo validation macro-F1 để truyền sang multi-output.

In [21]:
attention_status = load_planned_status("Stage 2 Attention", ATTENTION_PLANNED, ATTENTION_RUNS_ROOT, ["best_val_macro_f1", "best_val_loss", "test_macro_f1", "test_accuracy", "elapsed_minutes", "epochs_ran"])
display(attention_status)
top_attention_configs, top_attention_ranking = select_top_configs(ATTENTION_PLANNED, ATTENTION_RUNS_ROOT, "best_val_macro_f1", "best_val_loss", 4)
display(top_attention_ranking)

,stage,run,experiment,profile,hidden_size,attention_dim,num_layers,dropout,lr,purpose,status,run_dir,best_val_macro_f1,best_val_loss,test_macro_f1,test_accuracy,elapsed_minutes,epochs_ran,noise_sigma,bidirectional
0,Stage 2 Attention,S2_A01,S2_A01_top_gru_a32,selected,selected,32,selected,0.2,selected,top GRU -> attention a32,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.724154,1.542205,0.587413,0.661871,0.577504,34,NaN,NaN
1,Stage 2 Attention,S2_A02,S2_A02_top_gru_a48,selected,selected,48,selected,0.2,selected,top GRU -> attention a48,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.691956,1.496490,0.624697,0.676259,0.622833,37,NaN,NaN
2,Stage 2 Attention,S2_A03,S2_A03_second_gru_a32,selected,selected,32,selected,0.2,selected,second GRU branch,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.708761,1.534991,0.640343,0.705036,0.598936,36,NaN,NaN
3,Stage 2 Attention,S2_A04,S2_A04_second_gru_l2_d03,selected,selected,32,2,0.3,selected,stacked attention branch,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.718794,1.310522,0.641533,0.690647,0.537515,32,NaN,NaN
4,Stage 2 Attention,S2_A05,S2_A05_raw_shift_h128_a32_d03,raw_shift,128,32,1,0.3,0.001,h128 regularized,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.710086,1.449811,0.574418,0.633094,0.607337,35,NaN,NaN
5,Stage 2 Attention,S2_A06,S2_A06_raw_shift_h96_a64_d03,raw_shift,96,64,1,0.3,0.001,attention width upper,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.703188,1.527165,0.573389,0.640288,0.663559,40,NaN,NaN
6,Stage 2 Attention,S2_A07,S2_A07_phase_hampel_shift_h96_a32,phase_hampel_shift,96,32,1,0.2,0.001,denoise+shift stability,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.658903,1.580978,0.649403,0.690647,0.531154,31,NaN,NaN
7,Stage 2 Attention,S2_A08,S2_A08_phase_hampel_shift_noise_lr0005,phase_hampel_shift,96,32,1,0.3,0.0005,denoise+noise regularization,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.650561,1.302292,0.534851,0.618705,2.106173,35,0.01,NaN
8,Stage 2 Attention,S2_A09,S2_A09_raw_shift_bigru_h64_a32,raw_shift,64,32,1,0.2,0.001,BiGRU small probe,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.703504,0.872428,0.577029,0.611511,0.502108,21,NaN,True
9,Stage 2 Attention,S2_A10,S2_A10_raw_shift_h96_a48_lr0005,raw_shift,96,48,1,0.3,0.0005,A12-style regularized,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.710302,1.101874,0.674119,0.705036,0.902489,40,NaN,NaN

,stage,run,experiment,profile,hidden_size,attention_dim,num_layers,dropout,lr,purpose,status,run_dir,best_val_macro_f1,best_val_loss,noise_sigma,bidirectional
0,selection,S2_A01,S2_A01_top_gru_a32,selected,selected,32,selected,0.2,selected,top GRU -> attention a32,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.724154,1.542205,NaN,NaN
3,selection,S2_A04,S2_A04_second_gru_l2_d03,selected,selected,32,2,0.3,selected,stacked attention branch,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.718794,1.310522,NaN,NaN
9,selection,S2_A10,S2_A10_raw_shift_h96_a48_lr0005,raw_shift,96,48,1,0.3,0.0005,A12-style regularized,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.710302,1.101874,NaN,NaN
4,selection,S2_A05,S2_A05_raw_shift_h128_a32_d03,raw_shift,128,32,1,0.3,0.001,h128 regularized,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.710086,1.449811,NaN,NaN

## Stage 3 - Multi-output cell bottleneck attack (`S3_M01`-`S3_M10`)

Mục tiêu: dùng top Attention config, nâng cell head, thử cell weighting, focal/effective-number, denoise branch, stacked và BiGRU nhỏ.

### S3_M01 - top attention linear baseline

In [22]:
selected = pick_config(top_attention_configs, 0, fallback_config(profile='raw_shift', hidden_size=128, attention_dim=32, batch_size=32, learning_rate=0.0005, weight_decay=0.0001, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False))
config = train_multi.TrainConfig(experiment_name="S3_M01_top_attention_linear")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.cell_head_type = "linear"
config.cell_head_dropout = max(config.dropout, 0.2) if config.cell_head_type == "mlp" else 0.0
config.cell_loss_type = "cross_entropy"
config.cell_focal_gamma = 0.0
config.cell_class_weighting = "inverse_frequency"
config.cell_label_smoothing = 0.0
config.loss_weight_cell = 1.0

timed_train("Stage 3 Multi" if config.experiment_name.startswith("S3_M") else "Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  23%|██▎       | 23/100 [00:33<01:53,  1.47s/it, loss=6.04, score=0.511]

Stage 3 Multi | S3_M01_top_attention_linear | 0.59 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S3_M01_top_attention_linear',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.2,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'cell_head_type': 'linear',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.0,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 9,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5210660711962192,
 'epochs_ran': 24,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S3_M01_top_attention_linear',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.9,
 'val_presence_macro_f1': 0.6546863988724454,
 'val_presence_weighted_f1': 0.9124735729386892,
 'val_presence_macro_precision': 0.626984126984127,
 'val_presence_macro_recall': 0.7121212121212122,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.6285714285714286,
 'val_pose_macro_f1': 0.5524807916477628,
 'val_pose_weighted_f1': 0.6273712428115058,
 'val_pose_macro_precision': 0.569937794937795,
 'val_pose_macro_recall': 0.5556954164644582,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.25757575757575757,
 'val_cell_masked_macro_f1': 0.20722828086834877,
 'val_cell_masked_weighted_f1': 0.2600759986699175,
 'val_cell_masked_macro_precision': 0.2099119769119769,
 'val_cell_masked_macro_recall': 0.2686396087572558,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.38512621193446894,
 'val_center_m_rmse': 0.8913542124193999,
 'val_center_norm_rmse': 0.3301311866036801,
 'val_center_score': 0.6698688133963199,
 'val_center_mean_error_m': 0.7984535265585517,
 'val_center_support': 132.0,
 'val_loss_total': 4.4518251146589005,
 'val_loss_presence': 0.07463940900883505,
 'val_loss_cell': 3.2370745250156947,
 'val_loss_pose': 1.112743446656636,
 'val_loss_center': 0.027367774503571647,
 'val_loss': 4.4518251146589005,
 'test_presence_accuracy': 0.9136690647482014,
 'test_presence_macro_f1': 0.7454212454212454,
 'test_presence_weighted_f1': 0.925580414789048,
 'test_presence_macro_precision': 0.6976856316297011,
 'test_presence_macro_recall': 0.8504273504273505,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6546762589928058,
 'test_pose_macro_f1': 0.6103548053474019,
 'test_pose_weighted_f1': 0.6600704728334056,
 'test_pose_macro_precision': 0.6130427170868347,
 'test_pose_macro_recall': 0.6293042081075246,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.19230769230769232,
 'test_cell_masked_macro_f1': 0.10875833672118503,
 'test_cell_masked_weighted_f1': 0.1930878947906812,
 'test_cell_masked_macro_precision': 0.1275472948104527,
 'test_cell_masked_macro_recall': 0.12404906204906205,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.346669721030272,
 'test_center_m_rmse': 0.8411568702359213,
 'test_center_norm_rmse': 0.3115395778628952,
 'test_center_score': 0.6884604221371048,
 'test_center_mean_error_m': 0.7401440665080575,
 'test_center_support': 130.0,
 'test_loss_total': 4.293753304927469,
 'test_loss_presence': 0.0595307601012772,
 'test_loss_cell': 3.131194485177239,
 'test_loss_pose': 1.0787602362872886,
 'test_loss_center': 0.02426771457782752,
 'test_loss': 4.293753304927469,
 'elapsed_minutes': 0.5941665416670731}

### S3_M02 - top attention MLP cell head

In [23]:
selected = pick_config(top_attention_configs, 0, fallback_config(profile='raw_shift', hidden_size=128, attention_dim=32, batch_size=32, learning_rate=0.0005, weight_decay=0.0001, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False))
config = train_multi.TrainConfig(experiment_name="S3_M02_top_attention_mlp")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.cell_head_type = "mlp"
config.cell_head_dropout = max(config.dropout, 0.2) if config.cell_head_type == "mlp" else 0.0
config.cell_loss_type = "cross_entropy"
config.cell_focal_gamma = 0.0
config.cell_class_weighting = "inverse_frequency"
config.cell_label_smoothing = 0.0
config.loss_weight_cell = 1.0

timed_train("Stage 3 Multi" if config.experiment_name.startswith("S3_M") else "Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  61%|██████    | 61/100 [01:30<00:57,  1.48s/it, loss=8.63, score=0.544]

Stage 3 Multi | S3_M02_top_attention_mlp | 1.54 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S3_M02_top_attention_mlp',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.2,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.2,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 47,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5595243255883979,
 'epochs_ran': 62,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S3_M02_top_attention_mlp',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.9285714285714286,
 'val_presence_macro_f1': 0.7307692307692308,
 'val_presence_weighted_f1': 0.9351648351648351,
 'val_presence_macro_precision': 0.6966145833333334,
 'val_presence_macro_recall': 0.7859848484848485,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.7357142857142858,
 'val_pose_macro_f1': 0.6765285643540393,
 'val_pose_weighted_f1': 0.7326953594793144,
 'val_pose_macro_precision': 0.6964973251500766,
 'val_pose_macro_recall': 0.6636332724579194,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.25757575757575757,
 'val_cell_masked_macro_f1': 0.16725529758095053,
 'val_cell_masked_weighted_f1': 0.2568519984678682,
 'val_cell_masked_macro_precision': 0.16794449994449995,
 'val_cell_masked_macro_recall': 0.1746821936233701,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.37257194671441207,
 'val_center_m_rmse': 0.9084306449081152,
 'val_center_norm_rmse': 0.33645579035062906,
 'val_center_score': 0.6635442096493709,
 'val_center_mean_error_m': 0.7874943397888212,
 'val_center_support': 132.0,
 'val_loss_total': 8.157146399361746,
 'val_loss_presence': 0.1119090706642185,
 'val_loss_cell': 6.529566478729248,
 'val_loss_pose': 1.4869312184197563,
 'val_loss_center': 0.028739573274339947,
 'val_loss': 8.157146399361746,
 'test_presence_accuracy': 0.9064748201438849,
 'test_presence_macro_f1': 0.6919011082693947,
 'test_presence_weighted_f1': 0.9157236870350267,
 'test_presence_macro_precision': 0.6625714285714286,
 'test_presence_macro_recall': 0.7431623931623932,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.7050359712230215,
 'test_pose_macro_f1': 0.6857268951729413,
 'test_pose_weighted_f1': 0.7085646287325547,
 'test_pose_macro_precision': 0.6749368267404751,
 'test_pose_macro_recall': 0.7034836587204378,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.23846153846153847,
 'test_cell_masked_macro_f1': 0.15609375374081258,
 'test_cell_masked_weighted_f1': 0.23671014756987607,
 'test_cell_masked_macro_precision': 0.15622943722943725,
 'test_cell_masked_macro_recall': 0.16606105006105007,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.3527340088899319,
 'test_center_m_rmse': 0.8688845611239663,
 'test_center_norm_rmse': 0.32180909385985673,
 'test_center_score': 0.6781909061401432,
 'test_center_mean_error_m': 0.7527424942064909,
 'test_center_support': 130.0,
 'test_loss_total': 8.71820505745977,
 'test_loss_presence': 0.0922967431356581,
 'test_loss_cell': 7.1485886093523865,
 'test_loss_pose': 1.4510982499705802,
 'test_loss_center': 0.026221422679561505,
 'test_loss': 8.71820505745977,
 'elapsed_minutes': 1.5364738566665135}

### S3_M03 - raw_shift h128 MLP

In [24]:
selected = fallback_config(profile='raw_shift', hidden_size=128, attention_dim=32, batch_size=32, learning_rate=0.0005, weight_decay=0.0001, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False)
config = train_multi.TrainConfig(experiment_name="S3_M03_raw_shift_h128_mlp")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.cell_head_type = "mlp"
config.cell_head_dropout = max(config.dropout, 0.2) if config.cell_head_type == "mlp" else 0.0
config.cell_loss_type = "cross_entropy"
config.cell_focal_gamma = 0.0
config.cell_class_weighting = "inverse_frequency"
config.cell_label_smoothing = 0.0
config.loss_weight_cell = 1.0

timed_train("Stage 3 Multi" if config.experiment_name.startswith("S3_M") else "Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  33%|███▎      | 33/100 [00:49<01:39,  1.49s/it, loss=5.89, score=0.489]

Stage 3 Multi | S3_M03_raw_shift_h128_mlp | 0.85 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S3_M03_raw_shift_h128_mlp',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.3,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 19,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5176766631975883,
 'epochs_ran': 34,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S3_M03_raw_shift_h128_mlp',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.8642857142857143,
 'val_presence_macro_f1': 0.655395776655007,
 'val_presence_weighted_f1': 0.8930320359780134,
 'val_presence_macro_precision': 0.621887774061687,
 'val_presence_macro_recall': 0.8106060606060606,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.65,
 'val_pose_macro_f1': 0.641295107833191,
 'val_pose_weighted_f1': 0.6520864213195803,
 'val_pose_macro_precision': 0.6302632941288404,
 'val_pose_macro_recall': 0.668803159561697,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.17424242424242425,
 'val_cell_masked_macro_f1': 0.11126952360456255,
 'val_cell_masked_weighted_f1': 0.16008992189445218,
 'val_cell_masked_macro_precision': 0.14273160173160174,
 'val_cell_masked_macro_recall': 0.1417181641887524,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.3890787290239876,
 'val_center_m_rmse': 0.9105851497415122,
 'val_center_norm_rmse': 0.3372537553024073,
 'val_center_score': 0.6627462446975927,
 'val_center_mean_error_m': 0.8119753078737713,
 'val_center_support': 132.0,
 'val_loss_total': 4.511671672548567,
 'val_loss_presence': 0.06241554665778364,
 'val_loss_cell': 3.4866687979016984,
 'val_loss_pose': 0.9338457380022321,
 'val_loss_center': 0.028741459122725896,
 'val_loss': 4.511671672548567,
 'test_presence_accuracy': 0.8776978417266187,
 'test_presence_macro_f1': 0.6913934961473162,
 'test_presence_weighted_f1': 0.9001233648056087,
 'test_presence_macro_precision': 0.6505439005439005,
 'test_presence_macro_recall': 0.8311965811965811,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6762589928057554,
 'test_pose_macro_f1': 0.6551908340578549,
 'test_pose_weighted_f1': 0.6811213435202039,
 'test_pose_macro_precision': 0.6363342149056435,
 'test_pose_macro_recall': 0.6998080254865998,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.13846153846153847,
 'test_cell_masked_macro_f1': 0.09327777777777778,
 'test_cell_masked_weighted_f1': 0.12506410256410258,
 'test_cell_masked_macro_precision': 0.12565079365079365,
 'test_cell_masked_macro_recall': 0.11755555555555555,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.3686842305155901,
 'test_center_m_rmse': 0.8836588138005017,
 'test_center_norm_rmse': 0.3272810377300593,
 'test_center_score': 0.6727189622699408,
 'test_center_mean_error_m': 0.780982244777105,
 'test_center_support': 130.0,
 'test_loss_total': 4.907503385337995,
 'test_loss_presence': 0.062130987469991336,
 'test_loss_cell': 3.8032829246932653,
 'test_loss_pose': 1.015306890439644,
 'test_loss_center': 0.026782610915976463,
 'test_loss': 4.907503385337995,
 'elapsed_minutes': 0.8460447233335192}

### S3_M04 - raw_shift h128 MLP cell2

In [25]:
selected = fallback_config(profile='raw_shift', hidden_size=128, attention_dim=32, batch_size=32, learning_rate=0.0005, weight_decay=0.0001, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False)
config = train_multi.TrainConfig(experiment_name="S3_M04_raw_shift_h128_mlp_cell2")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.cell_head_type = "mlp"
config.cell_head_dropout = max(config.dropout, 0.2) if config.cell_head_type == "mlp" else 0.0
config.cell_loss_type = "cross_entropy"
config.cell_focal_gamma = 0.0
config.cell_class_weighting = "inverse_frequency"
config.cell_label_smoothing = 0.0
config.loss_weight_cell = 2.0

timed_train("Stage 3 Multi" if config.experiment_name.startswith("S3_M") else "Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  53%|█████▎    | 53/100 [01:20<01:11,  1.52s/it, loss=13.8, score=0.527]

Stage 3 Multi | S3_M04_raw_shift_h128_mlp_cell2 | 1.37 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S3_M04_raw_shift_h128_mlp_cell2',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.3,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 39,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5428810855391624,
 'epochs_ran': 54,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S3_M04_raw_shift_h128_mlp_cell2',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.8928571428571429,
 'val_presence_macro_f1': 0.6447301641008291,
 'val_presence_weighted_f1': 0.9077023467143583,
 'val_presence_macro_precision': 0.6173333333333333,
 'val_presence_macro_recall': 0.7083333333333333,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.6571428571428571,
 'val_pose_macro_f1': 0.5804199665937294,
 'val_pose_weighted_f1': 0.6631967217061767,
 'val_pose_macro_precision': 0.5966888801347052,
 'val_pose_macro_recall': 0.5892753377946923,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.25,
 'val_cell_masked_macro_f1': 0.2658808141599904,
 'val_cell_masked_weighted_f1': 0.24119626341472952,
 'val_cell_masked_macro_precision': 0.26196825396825396,
 'val_cell_masked_macro_recall': 0.28487748852454736,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.36127777346833184,
 'val_center_m_rmse': 0.8626678315558496,
 'val_center_norm_rmse': 0.319506602697899,
 'val_center_score': 0.680493397302101,
 'val_center_mean_error_m': 0.759305549636832,
 'val_center_support': 132.0,
 'val_loss_total': 11.916616548810687,
 'val_loss_presence': 0.08471194558909961,
 'val_loss_cell': 5.353386197771345,
 'val_loss_pose': 1.0992385123457227,
 'val_loss_center': 0.02589374142033713,
 'val_loss': 11.916616548810687,
 'test_presence_accuracy': 0.9064748201438849,
 'test_presence_macro_f1': 0.7333628449166298,
 'test_presence_weighted_f1': 0.9203856038675037,
 'test_presence_macro_precision': 0.6861799816345271,
 'test_presence_macro_recall': 0.8465811965811966,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6546762589928058,
 'test_pose_macro_f1': 0.6217755315292262,
 'test_pose_weighted_f1': 0.6597174495065837,
 'test_pose_macro_precision': 0.629889588731052,
 'test_pose_macro_recall': 0.6421329232235923,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.18461538461538463,
 'test_cell_masked_macro_f1': 0.1222902487799513,
 'test_cell_masked_weighted_f1': 0.18820507271484213,
 'test_cell_masked_macro_precision': 0.1397676317490559,
 'test_cell_masked_macro_recall': 0.13797335997335997,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.3493092029140546,
 'test_center_m_rmse': 0.8548193957993417,
 'test_center_norm_rmse': 0.31659977332907,
 'test_center_score': 0.68340022667093,
 'test_center_mean_error_m': 0.7493018058817539,
 'test_center_support': 130.0,
 'test_loss_total': 13.206136542258502,
 'test_loss_presence': 0.04347879766560287,
 'test_loss_cell': 6.01693463840073,
 'test_loss_pose': 1.1032596363438119,
 'test_loss_center': 0.025528780097584074,
 'test_loss': 13.206136542258502,
 'elapsed_minutes': 1.3701726183334055}

### S3_M05 - raw_shift h128 MLP focal

In [26]:
selected = fallback_config(profile='raw_shift', hidden_size=128, attention_dim=32, batch_size=32, learning_rate=0.0005, weight_decay=0.0001, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False)
config = train_multi.TrainConfig(experiment_name="S3_M05_raw_shift_h128_mlp_focal")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.cell_head_type = "mlp"
config.cell_head_dropout = max(config.dropout, 0.2) if config.cell_head_type == "mlp" else 0.0
config.cell_loss_type = "focal"
config.cell_focal_gamma = 2.0
config.cell_class_weighting = "inverse_frequency"
config.cell_label_smoothing = 0.0
config.loss_weight_cell = 2.0

timed_train("Stage 3 Multi" if config.experiment_name.startswith("S3_M") else "Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  63%|██████▎   | 63/100 [01:39<00:58,  1.58s/it, loss=14.6, score=0.519]

Stage 3 Multi | S3_M05_raw_shift_h128_mlp_focal | 1.69 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S3_M05_raw_shift_h128_mlp_focal',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.3,
 'cell_loss_type': 'focal',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 2.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 49,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5502262365006576,
 'epochs_ran': 64,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S3_M05_raw_shift_h128_mlp_focal',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.8928571428571429,
 'val_presence_macro_f1': 0.6138996138996139,
 'val_presence_weighted_f1': 0.9045780474351903,
 'val_presence_macro_precision': 0.5956995760145366,
 'val_presence_macro_recall': 0.6496212121212122,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.6857142857142857,
 'val_pose_macro_f1': 0.6044258701401558,
 'val_pose_weighted_f1': 0.6864621466050038,
 'val_pose_macro_precision': 0.6147814786291875,
 'val_pose_macro_recall': 0.6030832545784272,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.3181818181818182,
 'val_cell_masked_macro_f1': 0.3075283812521664,
 'val_cell_masked_weighted_f1': 0.31730706065744424,
 'val_cell_masked_macro_precision': 0.3364203835380306,
 'val_cell_masked_macro_recall': 0.3462905460552519,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.3609542330218987,
 'val_center_m_rmse': 0.8773620888935257,
 'val_center_norm_rmse': 0.32494891928930575,
 'val_center_score': 0.6750510807106942,
 'val_center_mean_error_m': 0.7630667704580457,
 'val_center_support': 132.0,
 'val_loss_total': 13.506320817129952,
 'val_loss_presence': 0.14449109906064614,
 'val_loss_cell': 5.9997816630772185,
 'val_loss_pose': 1.3355232047183172,
 'val_loss_center': 0.026743145074163165,
 'val_loss': 13.506320817129952,
 'test_presence_accuracy': 0.8992805755395683,
 'test_presence_macro_f1': 0.7029914529914529,
 'test_presence_weighted_f1': 0.9131771505872225,
 'test_presence_macro_precision': 0.664175506268081,
 'test_presence_macro_recall': 0.791025641025641,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.7050359712230215,
 'test_pose_macro_f1': 0.6755028948110979,
 'test_pose_weighted_f1': 0.7091161938729162,
 'test_pose_macro_precision': 0.695515873015873,
 'test_pose_macro_recall': 0.6782792258846214,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.2076923076923077,
 'test_cell_masked_macro_f1': 0.10682501801753384,
 'test_cell_masked_weighted_f1': 0.22369958783164826,
 'test_cell_masked_macro_precision': 0.1282775655716832,
 'test_cell_masked_macro_recall': 0.11192962592962592,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.33708986937999724,
 'test_center_m_rmse': 0.8392535410196725,
 'test_center_norm_rmse': 0.310834641210163,
 'test_center_score': 0.689165358789837,
 'test_center_mean_error_m': 0.7274011518576766,
 'test_center_support': 130.0,
 'test_loss_total': 11.946082497672212,
 'test_loss_presence': 0.059434525299274614,
 'test_loss_cell': 5.316319338709331,
 'test_loss_pose': 1.2293331297181493,
 'test_loss_center': 0.024675956062918943,
 'test_loss': 11.946082497672212,
 'elapsed_minutes': 1.6923072683333884}

### S3_M06 - raw_shift h128 MLP effective focal

In [27]:
selected = fallback_config(profile='raw_shift', hidden_size=128, attention_dim=32, batch_size=32, learning_rate=0.0005, weight_decay=0.0001, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False)
config = train_multi.TrainConfig(experiment_name="S3_M06_raw_shift_h128_mlp_effective")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.cell_head_type = "mlp"
config.cell_head_dropout = max(config.dropout, 0.2) if config.cell_head_type == "mlp" else 0.0
config.cell_loss_type = "focal"
config.cell_focal_gamma = 1.5
config.cell_class_weighting = "effective_number"
config.cell_label_smoothing = 0.0
config.loss_weight_cell = 2.0

timed_train("Stage 3 Multi" if config.experiment_name.startswith("S3_M") else "Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  30%|███       | 30/100 [00:46<01:49,  1.56s/it, loss=5.66, score=0.493]

Stage 3 Multi | S3_M06_raw_shift_h128_mlp_effective | 0.81 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S3_M06_raw_shift_h128_mlp_effective',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.3,
 'cell_loss_type': 'focal',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 1.5,
 'cell_class_weighting': 'effective_number',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 16,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5059140109004859,
 'epochs_ran': 31,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S3_M06_raw_shift_h128_mlp_effective',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.85,
 'val_presence_macro_f1': 0.5960983651600494,
 'val_presence_weighted_f1': 0.879736227503778,
 'val_presence_macro_precision': 0.5784313725490196,
 'val_presence_macro_recall': 0.6856060606060606,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.65,
 'val_pose_macro_f1': 0.6197247879275529,
 'val_pose_weighted_f1': 0.6541748024345648,
 'val_pose_macro_precision': 0.6091630785010577,
 'val_pose_macro_recall': 0.6385668629153789,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.16666666666666666,
 'val_cell_masked_macro_f1': 0.1425945165945166,
 'val_cell_masked_weighted_f1': 0.1510254055708601,
 'val_cell_masked_macro_precision': 0.14373044602456367,
 'val_cell_masked_macro_recall': 0.1945019033254327,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.38526067606201675,
 'val_center_m_rmse': 0.9038564010654045,
 'val_center_norm_rmse': 0.33476162608017507,
 'val_center_score': 0.6652383739198249,
 'val_center_mean_error_m': 0.807444677250141,
 'val_center_support': 132.0,
 'val_loss_total': 4.205905505589077,
 'val_loss_presence': 0.06239030999796731,
 'val_loss_cell': 1.5813780307769776,
 'val_loss_pose': 0.9524762545313153,
 'val_loss_center': 0.028282873651811053,
 'val_loss': 4.205905505589077,
 'test_presence_accuracy': 0.8776978417266187,
 'test_presence_macro_f1': 0.6913934961473162,
 'test_presence_weighted_f1': 0.9001233648056087,
 'test_presence_macro_precision': 0.6505439005439005,
 'test_presence_macro_recall': 0.8311965811965811,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6618705035971223,
 'test_pose_macro_f1': 0.617135296215756,
 'test_pose_weighted_f1': 0.6691338887055417,
 'test_pose_macro_precision': 0.6100700886415172,
 'test_pose_macro_recall': 0.6441874509360691,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.13076923076923078,
 'test_cell_masked_macro_f1': 0.07583855360325949,
 'test_cell_masked_weighted_f1': 0.10629860335742689,
 'test_cell_masked_macro_precision': 0.06432323232323232,
 'test_cell_masked_macro_recall': 0.10996825396825397,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.35816603222718607,
 'test_center_m_rmse': 0.8604601002385289,
 'test_center_norm_rmse': 0.31868892139354654,
 'test_center_score': 0.6813110786064535,
 'test_center_mean_error_m': 0.7604344158676631,
 'test_center_support': 130.0,
 'test_loss_total': 4.081222057342529,
 'test_loss_presence': 0.05838924222257283,
 'test_loss_cell': 1.52730029950039,
 'test_loss_pose': 0.9429011559314865,
 'test_loss_center': 0.02533106335686694,
 'test_loss': 4.081222057342529,
 'elapsed_minutes': 0.8095674033334944}

### S3_M07 - phase_hampel_shift MLP

In [28]:
selected = fallback_config(profile='phase_hampel_shift', hidden_size=128, attention_dim=32, batch_size=32, learning_rate=0.001, weight_decay=0.0001, num_layers=1, dropout=0.2, noise_sigma=0.0, bidirectional=False)
config = train_multi.TrainConfig(experiment_name="S3_M07_phase_hampel_shift_mlp")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.cell_head_type = "mlp"
config.cell_head_dropout = max(config.dropout, 0.2) if config.cell_head_type == "mlp" else 0.0
config.cell_loss_type = "cross_entropy"
config.cell_focal_gamma = 0.0
config.cell_class_weighting = "inverse_frequency"
config.cell_label_smoothing = 0.0
config.loss_weight_cell = 1.0

timed_train("Stage 3 Multi" if config.experiment_name.startswith("S3_M") else "Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  79%|███████▉  | 79/100 [01:57<00:31,  1.49s/it, loss=12, score=0.526]

Stage 3 Multi | S3_M07_phase_hampel_shift_mlp | 1.99 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S3_M07_phase_hampel_shift_mlp',
 'profile': 'phase_hampel_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.2,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.2,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 65,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5375978722691467,
 'epochs_ran': 80,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S3_M07_phase_hampel_shift_mlp',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.9285714285714286,
 'val_presence_macro_f1': 0.6685606060606061,
 'val_presence_weighted_f1': 0.9285714285714286,
 'val_presence_macro_precision': 0.6685606060606061,
 'val_presence_macro_recall': 0.6685606060606061,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.75,
 'val_pose_macro_f1': 0.6711431624096341,
 'val_pose_weighted_f1': 0.74916885107144,
 'val_pose_macro_precision': 0.6866052586133723,
 'val_pose_macro_recall': 0.663972503895175,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.2727272727272727,
 'val_cell_masked_macro_f1': 0.15146249563640868,
 'val_cell_masked_weighted_f1': 0.24706448458095356,
 'val_cell_masked_macro_precision': 0.18675947454080447,
 'val_cell_masked_macro_recall': 0.16036267000972884,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.37960055600287335,
 'val_center_m_rmse': 0.9200919018611058,
 'val_center_norm_rmse': 0.34077477503006204,
 'val_center_score': 0.659225224969938,
 'val_center_mean_error_m': 0.8013048614528511,
 'val_center_support': 132.0,
 'val_loss_total': 11.764221218654088,
 'val_loss_presence': 0.19402398292108305,
 'val_loss_cell': 9.68785550253732,
 'val_loss_pose': 1.853206323300089,
 'val_loss_center': 0.029135288617440632,
 'val_loss': 11.764221218654088,
 'test_presence_accuracy': 0.935251798561151,
 'test_presence_macro_f1': 0.7457833773623247,
 'test_presence_weighted_f1': 0.9368307020711413,
 'test_presence_macro_precision': 0.7344961240310077,
 'test_presence_macro_recall': 0.7585470085470085,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6762589928057554,
 'test_pose_macro_f1': 0.6328464507136261,
 'test_pose_weighted_f1': 0.6752878897798994,
 'test_pose_macro_precision': 0.6252319109461967,
 'test_pose_macro_recall': 0.6486812965197587,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.23846153846153847,
 'test_cell_masked_macro_f1': 0.14218799918434807,
 'test_cell_masked_weighted_f1': 0.2380553173818894,
 'test_cell_masked_macro_precision': 0.16384981684981687,
 'test_cell_masked_macro_recall': 0.1478079698079698,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.3450540855526924,
 'test_center_m_rmse': 0.8636343732522263,
 'test_center_norm_rmse': 0.3198645804117176,
 'test_center_score': 0.6801354195882824,
 'test_center_mean_error_m': 0.7410456121432731,
 'test_center_support': 130.0,
 'test_loss_total': 13.838719855109565,
 'test_loss_presence': 0.10534579420743657,
 'test_loss_cell': 11.92939944232968,
 'test_loss_pose': 1.7781938100032668,
 'test_loss_center': 0.025780840582556003,
 'test_loss': 13.838719855109565,
 'elapsed_minutes': 1.991614164999919}

### S3_M08 - phase_hampel_shift MLP noise

In [29]:
selected = fallback_config(profile='phase_hampel_shift', hidden_size=128, attention_dim=32, batch_size=32, learning_rate=0.001, weight_decay=0.0001, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False)
config = train_multi.TrainConfig(experiment_name="S3_M08_phase_hampel_shift_mlp_noise")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.cell_head_type = "mlp"
config.cell_head_dropout = max(config.dropout, 0.2) if config.cell_head_type == "mlp" else 0.0
config.cell_loss_type = "cross_entropy"
config.cell_focal_gamma = 0.0
config.cell_class_weighting = "inverse_frequency"
config.cell_label_smoothing = 0.0
config.loss_weight_cell = 1.0
config.noise_sigma = 0.01
config.dropout = 0.3
timed_train("Stage 3 Multi" if config.experiment_name.startswith("S3_M") else "Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  41%|████      | 41/100 [02:56<04:13,  4.30s/it, loss=10.2, score=0.495]

Stage 3 Multi | S3_M08_phase_hampel_shift_mlp_noise | 2.97 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S3_M08_phase_hampel_shift_mlp_noise',
 'profile': 'phase_hampel_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'noise_sigma': 0.01,
 'num_layers': 1,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.3,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 27,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5105419754667277,
 'epochs_ran': 42,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S3_M08_phase_hampel_shift_mlp_noise',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.8928571428571429,
 'val_presence_macro_f1': 0.6447301641008291,
 'val_presence_weighted_f1': 0.9077023467143583,
 'val_presence_macro_precision': 0.6173333333333333,
 'val_presence_macro_recall': 0.7083333333333333,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.7071428571428572,
 'val_pose_macro_f1': 0.606206840426513,
 'val_pose_weighted_f1': 0.7052951796968149,
 'val_pose_macro_precision': 0.6216555713194368,
 'val_pose_macro_recall': 0.5997859250083012,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.20454545454545456,
 'val_cell_masked_macro_f1': 0.135010989010989,
 'val_cell_masked_weighted_f1': 0.2056207681207681,
 'val_cell_masked_macro_precision': 0.1327186147186147,
 'val_cell_masked_macro_recall': 0.15291052738111563,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.38325208611786366,
 'val_center_m_rmse': 0.9282062583427894,
 'val_center_norm_rmse': 0.3437800916714198,
 'val_center_score': 0.6562199083285802,
 'val_center_mean_error_m': 0.8008798516591679,
 'val_center_support': 132.0,
 'val_loss_total': 8.38632699421474,
 'val_loss_presence': 0.13275636517043624,
 'val_loss_cell': 6.583578191484723,
 'val_loss_pose': 1.640090868302754,
 'val_loss_center': 0.029901429691484998,
 'val_loss': 8.38632699421474,
 'test_presence_accuracy': 0.8992805755395683,
 'test_presence_macro_f1': 0.7029914529914529,
 'test_presence_weighted_f1': 0.9131771505872225,
 'test_presence_macro_precision': 0.664175506268081,
 'test_presence_macro_recall': 0.791025641025641,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6402877697841727,
 'test_pose_macro_f1': 0.5961353329210473,
 'test_pose_weighted_f1': 0.6413376571470096,
 'test_pose_macro_precision': 0.5951839826839826,
 'test_pose_macro_recall': 0.6042304504065085,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.15384615384615385,
 'test_cell_masked_macro_f1': 0.09325186643147208,
 'test_cell_masked_weighted_f1': 0.15518469695930304,
 'test_cell_masked_macro_precision': 0.09772222222222222,
 'test_cell_masked_macro_recall': 0.10478388278388279,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.3655539415203608,
 'test_center_m_rmse': 0.8830045578976247,
 'test_center_norm_rmse': 0.32703872185232996,
 'test_center_score': 0.67296127814767,
 'test_center_mean_error_m': 0.7812965444220172,
 'test_center_support': 130.0,
 'test_loss_total': 8.830640947218422,
 'test_loss_presence': 0.09390394915592112,
 'test_loss_cell': 6.747628908363177,
 'test_loss_pose': 1.9620841475699444,
 'test_loss_center': 0.027023986866362662,
 'test_loss': 8.830640947218422,
 'elapsed_minutes': 2.96759817666704}

### S3_M09 - raw_shift MLP num_layers2

In [30]:
selected = fallback_config(profile='raw_shift', hidden_size=128, attention_dim=32, batch_size=32, learning_rate=0.0005, weight_decay=0.0001, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False)
config = train_multi.TrainConfig(experiment_name="S3_M09_raw_shift_mlp_l2_d03")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.cell_head_type = "mlp"
config.cell_head_dropout = max(config.dropout, 0.2) if config.cell_head_type == "mlp" else 0.0
config.cell_loss_type = "cross_entropy"
config.cell_focal_gamma = 0.0
config.cell_class_weighting = "inverse_frequency"
config.cell_label_smoothing = 0.0
config.loss_weight_cell = 1.0
config.num_layers = 2
config.dropout = 0.3
timed_train("Stage 3 Multi" if config.experiment_name.startswith("S3_M") else "Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  73%|███████▎  | 73/100 [01:56<00:43,  1.60s/it, loss=9.36, score=0.543]

Stage 3 Multi | S3_M09_raw_shift_mlp_l2_d03 | 1.97 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S3_M09_raw_shift_mlp_l2_d03',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 2,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.3,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 59,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5641513552422177,
 'epochs_ran': 74,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S3_M09_raw_shift_mlp_l2_d03',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.9071428571428571,
 'val_presence_macro_f1': 0.5929322299261911,
 'val_presence_weighted_f1': 0.9096974150877082,
 'val_presence_macro_precision': 0.5882103477523325,
 'val_presence_macro_recall': 0.5984848484848485,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.7428571428571429,
 'val_pose_macro_f1': 0.6892917719985389,
 'val_pose_weighted_f1': 0.7398892613930208,
 'val_pose_macro_precision': 0.7046280050481731,
 'val_pose_macro_recall': 0.6802883387397511,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.24242424242424243,
 'val_cell_masked_macro_f1': 0.29987974987974986,
 'val_cell_masked_weighted_f1': 0.2462128500007288,
 'val_cell_masked_macro_precision': 0.3058295038295038,
 'val_cell_masked_macro_recall': 0.3352610265551442,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.3679357728158886,
 'val_center_m_rmse': 0.8788455007490732,
 'val_center_norm_rmse': 0.32549833083560886,
 'val_center_score': 0.6745016691643911,
 'val_center_mean_error_m': 0.7717259117991677,
 'val_center_support': 132.0,
 'val_loss_total': 9.021899250575474,
 'val_loss_presence': 0.2778489159752748,
 'val_loss_cell': 6.917473547799247,
 'val_loss_pose': 1.7999683822904313,
 'val_loss_center': 0.026608152155365262,
 'val_loss': 9.021899250575474,
 'test_presence_accuracy': 0.8992805755395683,
 'test_presence_macro_f1': 0.6544744318181819,
 'test_presence_weighted_f1': 0.907650016350556,
 'test_presence_macro_precision': 0.634004884004884,
 'test_presence_macro_recall': 0.6876068376068376,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6906474820143885,
 'test_pose_macro_f1': 0.624822179923863,
 'test_pose_weighted_f1': 0.6939598411433145,
 'test_pose_macro_precision': 0.6234237950499348,
 'test_pose_macro_recall': 0.6385957015236777,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.23076923076923078,
 'test_cell_masked_macro_f1': 0.1454700994911521,
 'test_cell_masked_weighted_f1': 0.23020284393968604,
 'test_cell_masked_macro_precision': 0.14555011655011654,
 'test_cell_masked_macro_recall': 0.15336596736596736,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.32318086532446055,
 'test_center_m_rmse': 0.7988091478176221,
 'test_center_norm_rmse': 0.2958552360322,
 'test_center_score': 0.7041447639678,
 'test_center_mean_error_m': 0.6978024470493404,
 'test_center_support': 130.0,
 'test_loss_total': 9.409681762722757,
 'test_loss_presence': 0.12683127536404903,
 'test_loss_cell': 7.2830657255735325,
 'test_loss_pose': 1.9775729711107213,
 'test_loss_center': 0.0222117643428149,
 'test_loss': 9.409681762722757,
 'elapsed_minutes': 1.9709646966667302}

### S3_M10 - raw_shift BiGRU MLP

In [31]:
selected = fallback_config(profile='raw_shift', hidden_size=64, attention_dim=32, batch_size=32, learning_rate=0.0005, weight_decay=0.0001, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False)
config = train_multi.TrainConfig(experiment_name="S3_M10_raw_shift_bigru_mlp")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.cell_head_type = "mlp"
config.cell_head_dropout = max(config.dropout, 0.2) if config.cell_head_type == "mlp" else 0.0
config.cell_loss_type = "cross_entropy"
config.cell_focal_gamma = 0.0
config.cell_class_weighting = "inverse_frequency"
config.cell_label_smoothing = 0.0
config.loss_weight_cell = 1.0
config.bidirectional = True
timed_train("Stage 3 Multi" if config.experiment_name.startswith("S3_M") else "Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  43%|████▎     | 43/100 [01:12<01:35,  1.68s/it, loss=5.71, score=0.491]

Stage 3 Multi | S3_M10_raw_shift_bigru_mlp | 1.23 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S3_M10_raw_shift_bigru_mlp',
 'profile': 'raw_shift',
 'hidden_size': 64,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': True,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.3,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 29,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.49922259569429844,
 'epochs_ran': 44,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S3_M10_raw_shift_bigru_mlp',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.8642857142857143,
 'val_presence_macro_f1': 0.5827450980392157,
 'val_presence_weighted_f1': 0.8863193277310925,
 'val_presence_macro_precision': 0.5679100908656145,
 'val_presence_macro_recall': 0.634469696969697,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.65,
 'val_pose_macro_f1': 0.5625659807959821,
 'val_pose_weighted_f1': 0.6544144183192623,
 'val_pose_macro_precision': 0.5666219727180318,
 'val_pose_macro_recall': 0.5606521864064774,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.23484848484848486,
 'val_cell_masked_macro_f1': 0.17814280055456524,
 'val_cell_masked_weighted_f1': 0.22197543617998164,
 'val_cell_masked_macro_precision': 0.1872875816993464,
 'val_cell_masked_macro_recall': 0.20734807675984146,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.3804104189868226,
 'val_center_m_rmse': 0.8817214508082278,
 'val_center_norm_rmse': 0.32656349661256917,
 'val_center_score': 0.6734365033874308,
 'val_center_mean_error_m': 0.7889745780594325,
 'val_center_support': 132.0,
 'val_loss_total': 5.282191937310355,
 'val_loss_presence': 0.11125895913158144,
 'val_loss_cell': 4.051641362054007,
 'val_loss_pose': 1.092322085584913,
 'val_loss_center': 0.026969407711710247,
 'val_loss': 5.282191937310355,
 'test_presence_accuracy': 0.9064748201438849,
 'test_presence_macro_f1': 0.6919011082693947,
 'test_presence_weighted_f1': 0.9157236870350267,
 'test_presence_macro_precision': 0.6625714285714286,
 'test_presence_macro_recall': 0.7431623931623932,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6402877697841727,
 'test_pose_macro_f1': 0.5942446490791439,
 'test_pose_weighted_f1': 0.6415192932761804,
 'test_pose_macro_precision': 0.5844753533597347,
 'test_pose_macro_recall': 0.6160297887630616,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.16923076923076924,
 'test_cell_masked_macro_f1': 0.09580899293942773,
 'test_cell_masked_weighted_f1': 0.17392590686905066,
 'test_cell_masked_macro_precision': 0.11163003663003662,
 'test_cell_masked_macro_recall': 0.09634720834720835,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.3481034529896883,
 'test_center_m_rmse': 0.8350512812926225,
 'test_center_norm_rmse': 0.3092782484094043,
 'test_center_score': 0.6907217515905957,
 'test_center_mean_error_m': 0.7430669616511589,
 'test_center_support': 130.0,
 'test_loss_total': 5.255572133784671,
 'test_loss_presence': 0.07074893980199913,
 'test_loss_cell': 4.086970818986138,
 'test_loss_pose': 1.0738215780944276,
 'test_loss_center': 0.024030754329274883,
 'test_loss': 5.255572133784671,
 'elapsed_minutes': 1.2318736899993383}

## Stage 3 selection

Chọn top 3 Multi-output theo composite validation. Cell macro-F1 được hiển thị riêng vì đây là bottleneck chính.

In [32]:
multi_status = load_planned_status("Stage 3 Multi", MULTI_PLANNED, MULTI_RUNS_ROOT, ["best_val_composite_score", "val_loss", "val_cell_masked_macro_f1", "test_cell_masked_macro_f1", "test_pose_macro_f1", "elapsed_minutes", "epochs_ran"])
display(multi_status)
top_multi_configs, top_multi_ranking = select_top_configs(MULTI_PLANNED, MULTI_RUNS_ROOT, "best_val_composite_score", "val_loss", 3)
display(top_multi_ranking)

,stage,run,experiment,profile,cell_head_type,cell_loss_type,purpose,status,run_dir,best_val_composite_score,...,elapsed_minutes,epochs_ran,loss_weight_cell,cell_focal_gamma,cell_class_weighting,noise_sigma,dropout,num_layers,bidirectional,hidden_size
0,Stage 3 Multi,S3_M01,S3_M01_top_attention_linear,selected,linear,cross_entropy,multi baseline từ top attention,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.521066,...,0.594167,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Stage 3 Multi,S3_M02,S3_M02_top_attention_mlp,selected,mlp,cross_entropy,MLP cell head,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.559524,...,1.536474,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Stage 3 Multi,S3_M03,S3_M03_raw_shift_h128_mlp,raw_shift,mlp,cross_entropy,raw_shift h128 MLP,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.517677,...,0.846045,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Stage 3 Multi,S3_M04,S3_M04_raw_shift_h128_mlp_cell2,raw_shift,mlp,cross_entropy,cell loss x2,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.542881,...,1.370173,54,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Stage 3 Multi,S3_M05,S3_M05_raw_shift_h128_mlp_focal,raw_shift,mlp,focal,focal cell hard examples,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.550226,...,1.692307,64,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
5,Stage 3 Multi,S3_M06,S3_M06_raw_shift_h128_mlp_effective,raw_shift,mlp,focal,effective-number class balance,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.505914,...,0.809567,31,2.0,1.5,effective_number,NaN,NaN,NaN,NaN,NaN
6,Stage 3 Multi,S3_M07,S3_M07_phase_hampel_shift_mlp,phase_hampel_shift,mlp,cross_entropy,denoise multi baseline,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.537598,...,1.991614,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Stage 3 Multi,S3_M08,S3_M08_phase_hampel_shift_mlp_noise,phase_hampel_shift,mlp,cross_entropy,denoise+noise multi,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.510542,...,2.967598,42,NaN,NaN,NaN,0.01,0.3,NaN,NaN,NaN
8,Stage 3 Multi,S3_M09,S3_M09_raw_shift_mlp_l2_d03,raw_shift,mlp,cross_entropy,stacked multi,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.564151,...,1.970965,74,NaN,NaN,NaN,NaN,0.3,2.0,NaN,NaN
9,Stage 3 Multi,S3_M10,S3_M10_raw_shift_bigru_mlp,raw_shift,mlp,cross_entropy,BiGRU multi probe,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.499223,...,1.231874,44,NaN,NaN,NaN,NaN,NaN,NaN,True,64.0

,stage,run,experiment,profile,cell_head_type,cell_loss_type,purpose,status,run_dir,best_val_composite_score,val_loss,loss_weight_cell,cell_focal_gamma,cell_class_weighting,noise_sigma,dropout,num_layers,bidirectional,hidden_size
8,selection,S3_M09,S3_M09_raw_shift_mlp_l2_d03,raw_shift,mlp,cross_entropy,stacked multi,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.564151,9.021899,NaN,NaN,NaN,NaN,0.3,2.0,NaN,NaN
1,selection,S3_M02,S3_M02_top_attention_mlp,selected,mlp,cross_entropy,MLP cell head,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.559524,8.157146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,selection,S3_M05,S3_M05_raw_shift_h128_mlp_focal,raw_shift,mlp,focal,focal cell hard examples,completed,c:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...,0.550226,13.506321,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN

## Stage 4 - Final confirmation and ablation (`S4_F01`-`S4_F08`)

Mục tiêu: xác nhận top candidates bằng seed khác và ablation nhỏ. Không mở search mới ở stage này.

### S4_F01 - attention top seed43

In [33]:
selected = pick_config(top_attention_configs, 0, fallback_config(profile="raw_shift", hidden_size=96, attention_dim=32, batch_size=32, learning_rate=1e-3, weight_decay=1e-4, num_layers=1, dropout=0.2, noise_sigma=0.0, bidirectional=False))
config = train_attention.TrainConfig(experiment_name="S4_F01_attention_top_seed43")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.seed = 43
timed_train("Stage 4 Attention Final", train_attention.train, config)

Attention-GRU:  44%|████▍     | 44/100 [00:46<00:58,  1.05s/it, val_f1=0.693, val_loss=1.75]

Stage 4 Attention Final | S4_F01_attention_top_seed43 | 0.79 min

{'phase_name': 'Attention-GRU',
 'profile': 'raw_shift',
 'experiment_name': 'S4_F01_attention_top_seed43',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.2,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'best_epoch': 30,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 45,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S4_F01_attention_top_seed43',
 'best_val_accuracy': 0.7428571428571429,
 'best_val_macro_f1': 0.699466585688649,
 'best_val_weighted_f1': 0.7443165710728736,
 'best_val_macro_precision': 0.7006870050001214,
 'best_val_macro_recall': 0.7039611057188833,
 'best_val_loss': 1.6568768892969403,
 'test_accuracy': 0.6762589928057554,
 'test_macro_f1': 0.619713355427641,
 'test_weighted_f1': 0.6779584391095181,
 'test_macro_precision': 0.6345570692044934,
 'test_macro_recall': 0.621238921360611,
 'test_loss': 2.0788408217670247,
 'elapsed_minutes': 0.7934816716665712}

### S4_F02 - attention second seed43

In [34]:
selected = pick_config(top_attention_configs, 1, fallback_config(profile="raw_shift", hidden_size=96, attention_dim=32, batch_size=32, learning_rate=1e-3, weight_decay=1e-4, num_layers=1, dropout=0.2, noise_sigma=0.0, bidirectional=False))
config = train_attention.TrainConfig(experiment_name="S4_F02_attention_second_seed43")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional"])
config.seed = 43
timed_train("Stage 4 Attention Final", train_attention.train, config)

Attention-GRU:  51%|█████     | 51/100 [01:01<00:59,  1.20s/it, val_f1=0.714, val_loss=1.93]

Stage 4 Attention Final | S4_F02_attention_second_seed43 | 1.05 min

{'phase_name': 'Attention-GRU',
 'profile': 'raw_shift',
 'experiment_name': 'S4_F02_attention_second_seed43',
 'hidden_size': 96,
 'attention_dim': 32,
 'dropout': 0.3,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'batch_size': 32,
 'noise_sigma': 0.0,
 'num_layers': 2,
 'bidirectional': False,
 'best_epoch': 37,
 'best_metric_name': 'val_macro_f1',
 'epochs_ran': 52,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\attention_gru\\S4_F02_attention_second_seed43',
 'best_val_accuracy': 0.7857142857142857,
 'best_val_macro_f1': 0.7343257248967608,
 'best_val_weighted_f1': 0.7787198454532654,
 'best_val_macro_precision': 0.7593437209375641,
 'best_val_macro_recall': 0.7293627557405941,
 'best_val_loss': 1.8822649904659816,
 'test_accuracy': 0.7122302158273381,
 'test_macro_f1': 0.6621387002092085,
 'test_weighted_f1': 0.7146179859359201,
 'test_macro_precision': 0.6640039791435568,
 'test_macro_recall': 0.6658575682583603,
 'test_loss': 2.097083669772251,
 'elapsed_minutes': 1.05167170833253}

### S4_F03 - multi top seed43

In [35]:
selected = pick_config(top_multi_configs, 0, fallback_config(profile="raw_shift", hidden_size=128, attention_dim=32, batch_size=32, learning_rate=5e-4, weight_decay=1e-4, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False, cell_head_type="mlp", cell_loss_type="cross_entropy", cell_focal_gamma=0.0, cell_label_smoothing=0.0, cell_class_weighting="inverse_frequency", loss_weight_cell=2.0))
config = train_multi.TrainConfig(experiment_name="S4_F03_multi_top_seed43")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional", "cell_head_type", "cell_loss_type", "cell_focal_gamma", "cell_label_smoothing", "cell_class_weighting", "loss_weight_cell"])
config.seed = 43

timed_train("Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  43%|████▎     | 43/100 [01:13<01:37,  1.70s/it, loss=9.3, score=0.537]

Stage 4 Multi Final | S4_F03_multi_top_seed43 | 1.25 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S4_F03_multi_top_seed43',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 2,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.0,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 29,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5505449056809086,
 'epochs_ran': 44,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S4_F03_multi_top_seed43',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.8857142857142857,
 'val_presence_macro_f1': 0.6053558844256518,
 'val_presence_weighted_f1': 0.8999697976442161,
 'val_presence_macro_precision': 0.5873015873015873,
 'val_presence_macro_recall': 0.6458333333333333,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.7357142857142858,
 'val_pose_macro_f1': 0.7173346190480813,
 'val_pose_weighted_f1': 0.7442511566580106,
 'val_pose_macro_precision': 0.7491774891774892,
 'val_pose_macro_recall': 0.701673488544354,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.2727272727272727,
 'val_cell_masked_macro_f1': 0.19673425769077946,
 'val_cell_masked_weighted_f1': 0.2668538465145843,
 'val_cell_masked_macro_precision': 0.2210989010989011,
 'val_cell_masked_macro_recall': 0.21808404667228196,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.35584669475528324,
 'val_center_m_rmse': 0.8565618855862625,
 'val_center_norm_rmse': 0.31724513844087837,
 'val_center_score': 0.6827548615591217,
 'val_center_mean_error_m': 0.7531358686574013,
 'val_center_support': 132.0,
 'val_loss_total': 7.899056870596749,
 'val_loss_presence': 0.14167082442768983,
 'val_loss_cell': 6.375203772953578,
 'val_loss_pose': 1.3567374842507498,
 'val_loss_center': 0.025445078100476946,
 'val_loss': 7.899056870596749,
 'test_presence_accuracy': 0.8992805755395683,
 'test_presence_macro_f1': 0.722,
 'test_presence_weighted_f1': 0.915251798561151,
 'test_presence_macro_precision': 0.6758771929824561,
 'test_presence_macro_recall': 0.8427350427350427,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6546762589928058,
 'test_pose_macro_f1': 0.6026663946850179,
 'test_pose_weighted_f1': 0.6532253159614257,
 'test_pose_macro_precision': 0.618325022316619,
 'test_pose_macro_recall': 0.6087587597343393,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.26153846153846155,
 'test_cell_masked_macro_f1': 0.17222812410913096,
 'test_cell_masked_weighted_f1': 0.26581108864861724,
 'test_cell_masked_macro_precision': 0.1962979242979243,
 'test_cell_masked_macro_recall': 0.1745891885891886,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.33936111147587117,
 'test_center_m_rmse': 0.8204927956240375,
 'test_center_norm_rmse': 0.3038862152366963,
 'test_center_score': 0.6961137847633037,
 'test_center_mean_error_m': 0.7209278022189147,
 'test_center_support': 130.0,
 'test_loss_total': 7.463863245874858,
 'test_loss_presence': 0.06901550225967126,
 'test_loss_cell': 5.540958560627999,
 'test_loss_pose': 1.8306967693267109,
 'test_loss_center': 0.02319238239751874,
 'test_loss': 7.463863245874858,
 'elapsed_minutes': 1.2511484633335688}

### S4_F04 - multi top seed44

In [36]:
selected = pick_config(top_multi_configs, 0, fallback_config(profile="raw_shift", hidden_size=128, attention_dim=32, batch_size=32, learning_rate=5e-4, weight_decay=1e-4, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False, cell_head_type="mlp", cell_loss_type="cross_entropy", cell_focal_gamma=0.0, cell_label_smoothing=0.0, cell_class_weighting="inverse_frequency", loss_weight_cell=2.0))
config = train_multi.TrainConfig(experiment_name="S4_F04_multi_top_seed44")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional", "cell_head_type", "cell_loss_type", "cell_focal_gamma", "cell_label_smoothing", "cell_class_weighting", "loss_weight_cell"])
config.seed = 44

timed_train("Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  31%|███       | 31/100 [00:50<01:52,  1.63s/it, loss=7.73, score=0.508]

Stage 4 Multi Final | S4_F04_multi_top_seed44 | 0.87 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S4_F04_multi_top_seed44',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 2,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.0,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 17,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5653010498029173,
 'epochs_ran': 32,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S4_F04_multi_top_seed44',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.8428571428571429,
 'val_presence_macro_f1': 0.6317551410808224,
 'val_presence_weighted_f1': 0.8787046525927443,
 'val_presence_macro_precision': 0.606612685560054,
 'val_presence_macro_recall': 0.7992424242424243,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.7285714285714285,
 'val_pose_macro_f1': 0.7103717270383937,
 'val_pose_weighted_f1': 0.7457929724596392,
 'val_pose_macro_precision': 0.7070728291316526,
 'val_pose_macro_recall': 0.7404217005951317,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.2878787878787879,
 'val_cell_masked_macro_f1': 0.2571700478171066,
 'val_cell_masked_weighted_f1': 0.2812306227970221,
 'val_cell_masked_macro_precision': 0.2819047619047619,
 'val_cell_masked_macro_recall': 0.2911060312236783,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.3816432198227355,
 'val_center_m_rmse': 0.9128503418595836,
 'val_center_norm_rmse': 0.3380927167246534,
 'val_center_score': 0.6619072832753465,
 'val_center_mean_error_m': 0.810931434694838,
 'val_center_support': 132.0,
 'val_loss_total': 4.954235662732805,
 'val_loss_presence': 0.05120690890720912,
 'val_loss_cell': 3.953860712051392,
 'val_loss_pose': 0.920457455090114,
 'val_loss_center': 0.028710425964423587,
 'val_loss': 4.954235662732805,
 'test_presence_accuracy': 0.8201438848920863,
 'test_presence_macro_f1': 0.6102949422451497,
 'test_presence_weighted_f1': 0.8592333938165156,
 'test_presence_macro_precision': 0.5936293436293436,
 'test_presence_macro_recall': 0.7487179487179487,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6474820143884892,
 'test_pose_macro_f1': 0.6019418676561533,
 'test_pose_weighted_f1': 0.6575483509296459,
 'test_pose_macro_precision': 0.6107232366630864,
 'test_pose_macro_recall': 0.6160619406535586,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.16153846153846155,
 'test_cell_masked_macro_f1': 0.11822945099649905,
 'test_cell_masked_weighted_f1': 0.17006376931953415,
 'test_cell_masked_macro_precision': 0.12509756909756908,
 'test_cell_masked_macro_recall': 0.14210767010767011,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.3464904444722029,
 'test_center_m_rmse': 0.834338758661231,
 'test_center_norm_rmse': 0.3090143521250243,
 'test_center_score': 0.6909856478749756,
 'test_center_mean_error_m': 0.7394755820446722,
 'test_center_support': 130.0,
 'test_loss_total': 5.128575407343803,
 'test_loss_presence': 0.05535774613670308,
 'test_loss_cell': 3.8091819046212616,
 'test_loss_pose': 1.240049156353628,
 'test_loss_center': 0.02398645546850112,
 'test_loss': 5.128575407343803,
 'elapsed_minutes': 0.8689813616666167}

### S4_F05 - multi second seed43

In [37]:
selected = pick_config(top_multi_configs, 1, fallback_config(profile="raw_shift", hidden_size=128, attention_dim=32, batch_size=32, learning_rate=5e-4, weight_decay=1e-4, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False, cell_head_type="mlp", cell_loss_type="cross_entropy", cell_focal_gamma=0.0, cell_label_smoothing=0.0, cell_class_weighting="inverse_frequency", loss_weight_cell=2.0))
config = train_multi.TrainConfig(experiment_name="S4_F05_multi_second_seed43")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional", "cell_head_type", "cell_loss_type", "cell_focal_gamma", "cell_label_smoothing", "cell_class_weighting", "loss_weight_cell"])
config.seed = 43

timed_train("Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  44%|████▍     | 44/100 [01:05<01:23,  1.49s/it, loss=11.5, score=0.548]

Stage 4 Multi Final | S4_F05_multi_second_seed43 | 1.12 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S4_F05_multi_second_seed43',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.2,
 'batch_size': 32,
 'learning_rate': 0.001,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.0,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 30,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5679054766860232,
 'epochs_ran': 45,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S4_F05_multi_second_seed43',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.9071428571428571,
 'val_presence_macro_f1': 0.6653796653796654,
 'val_presence_weighted_f1': 0.9173009744438315,
 'val_presence_macro_precision': 0.6380981223500908,
 'val_presence_macro_recall': 0.7159090909090908,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.75,
 'val_pose_macro_f1': 0.7115801023295567,
 'val_pose_weighted_f1': 0.7528716722682282,
 'val_pose_macro_precision': 0.7028649404425803,
 'val_pose_macro_recall': 0.7348351574672423,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.25,
 'val_cell_masked_macro_f1': 0.222581701522878,
 'val_cell_masked_weighted_f1': 0.26397953733069596,
 'val_cell_masked_macro_precision': 0.2772307692307692,
 'val_cell_masked_macro_recall': 0.22667309161426807,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.37732468810722686,
 'val_center_m_rmse': 0.8853828266196159,
 'val_center_norm_rmse': 0.32791956248800747,
 'val_center_score': 0.6720804375119925,
 'val_center_mean_error_m': 0.786014516949737,
 'val_center_support': 132.0,
 'val_loss_total': 9.928045572553362,
 'val_loss_presence': 0.1273838231872235,
 'val_loss_cell': 8.682053511483328,
 'val_loss_pose': 1.0915152720042638,
 'val_loss_center': 0.02709305627005441,
 'val_loss': 9.928045572553362,
 'test_presence_accuracy': 0.9136690647482014,
 'test_presence_macro_f1': 0.7263779527559056,
 'test_presence_weighted_f1': 0.9234407749391037,
 'test_presence_macro_precision': 0.6879032258064517,
 'test_presence_macro_recall': 0.7987179487179488,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6834532374100719,
 'test_pose_macro_f1': 0.6549397824397823,
 'test_pose_weighted_f1': 0.6862169425298922,
 'test_pose_macro_precision': 0.6473939226040066,
 'test_pose_macro_recall': 0.6813615866024908,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.24615384615384617,
 'test_cell_masked_macro_f1': 0.14025532575738525,
 'test_cell_masked_weighted_f1': 0.2510928788397544,
 'test_cell_masked_macro_precision': 0.14093395493395494,
 'test_cell_masked_macro_recall': 0.14457897657897656,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.32950950058606954,
 'test_center_m_rmse': 0.8139640172636075,
 'test_center_norm_rmse': 0.3014681513439612,
 'test_center_score': 0.6985318486560388,
 'test_center_mean_error_m': 0.7049892884652742,
 'test_center_support': 130.0,
 'test_loss_total': 10.663181181434247,
 'test_loss_presence': 0.09589407143745028,
 'test_loss_cell': 8.630772631803005,
 'test_loss_pose': 1.9138317588421938,
 'test_loss_center': 0.022682266216055093,
 'test_loss': 10.663181181434247,
 'elapsed_minutes': 1.1165745616657659}

### S4_F06 - multi linear head ablation

In [38]:
selected = pick_config(top_multi_configs, 0, fallback_config(profile="raw_shift", hidden_size=128, attention_dim=32, batch_size=32, learning_rate=5e-4, weight_decay=1e-4, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False, cell_head_type="mlp", cell_loss_type="cross_entropy", cell_focal_gamma=0.0, cell_label_smoothing=0.0, cell_class_weighting="inverse_frequency", loss_weight_cell=2.0))
config = train_multi.TrainConfig(experiment_name="S4_F06_multi_linear_ablation")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional", "cell_head_type", "cell_loss_type", "cell_focal_gamma", "cell_label_smoothing", "cell_class_weighting", "loss_weight_cell"])
config.seed = 43
config.cell_head_type = 'linear'
config.cell_head_dropout = 0.0
timed_train("Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  56%|█████▌    | 56/100 [01:27<01:08,  1.56s/it, loss=7.87, score=0.548]

Stage 4 Multi Final | S4_F06_multi_linear_ablation | 1.48 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S4_F06_multi_linear_ablation',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 2,
 'bidirectional': False,
 'cell_head_type': 'linear',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.0,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 42,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5682439108204228,
 'epochs_ran': 57,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S4_F06_multi_linear_ablation',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.9071428571428571,
 'val_presence_macro_f1': 0.6329905222827183,
 'val_presence_weighted_f1': 0.9139400224699681,
 'val_presence_macro_precision': 0.6169837914023961,
 'val_presence_macro_recall': 0.6571969696969697,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.7428571428571429,
 'val_pose_macro_f1': 0.7094115906045998,
 'val_pose_weighted_f1': 0.7479940694226408,
 'val_pose_macro_precision': 0.7228862112220774,
 'val_pose_macro_recall': 0.6995335368189829,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.25757575757575757,
 'val_cell_masked_macro_f1': 0.26110875111397325,
 'val_cell_masked_weighted_f1': 0.25781652561759116,
 'val_cell_masked_macro_precision': 0.3164362108479756,
 'val_cell_masked_macro_recall': 0.24595203489321135,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.3617566464412393,
 'val_center_m_rmse': 0.8924451000972099,
 'val_center_norm_rmse': 0.3305352207196003,
 'val_center_score': 0.6694647792803997,
 'val_center_mean_error_m': 0.766477177851478,
 'val_center_support': 132.0,
 'val_loss_total': 6.806227847508022,
 'val_loss_presence': 0.20156856019582067,
 'val_loss_cell': 4.798059327261789,
 'val_loss_pose': 1.7790553876331874,
 'val_loss_center': 0.027544548575367245,
 'val_loss': 6.806227847508022,
 'test_presence_accuracy': 0.9064748201438849,
 'test_presence_macro_f1': 0.6919011082693947,
 'test_presence_weighted_f1': 0.9157236870350267,
 'test_presence_macro_precision': 0.6625714285714286,
 'test_presence_macro_recall': 0.7431623931623932,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.7050359712230215,
 'test_pose_macro_f1': 0.6696420752145585,
 'test_pose_weighted_f1': 0.7143137911709273,
 'test_pose_macro_precision': 0.6886724386724387,
 'test_pose_macro_recall': 0.674498121253752,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.2692307692307692,
 'test_cell_masked_macro_f1': 0.2066459422930011,
 'test_cell_masked_weighted_f1': 0.27161734946802824,
 'test_cell_masked_macro_precision': 0.23663294600136706,
 'test_cell_masked_macro_recall': 0.21127072927072926,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.3329717875673221,
 'test_center_m_rmse': 0.8697680492352933,
 'test_center_norm_rmse': 0.3221363118782148,
 'test_center_score': 0.6778636881217852,
 'test_center_mean_error_m': 0.724589751647933,
 'test_center_support': 130.0,
 'test_loss_total': 6.47484485365504,
 'test_loss_presence': 0.13828907558600678,
 'test_loss_cell': 4.510195214113743,
 'test_loss_pose': 1.8004221247254515,
 'test_loss_center': 0.025938285581713957,
 'test_loss': 6.47484485365504,
 'elapsed_minutes': 1.48018021833268}

### S4_F07 - multi CE loss ablation

In [39]:
selected = pick_config(top_multi_configs, 0, fallback_config(profile="raw_shift", hidden_size=128, attention_dim=32, batch_size=32, learning_rate=5e-4, weight_decay=1e-4, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False, cell_head_type="mlp", cell_loss_type="cross_entropy", cell_focal_gamma=0.0, cell_label_smoothing=0.0, cell_class_weighting="inverse_frequency", loss_weight_cell=2.0))
config = train_multi.TrainConfig(experiment_name="S4_F07_multi_ce_ablation")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional", "cell_head_type", "cell_loss_type", "cell_focal_gamma", "cell_label_smoothing", "cell_class_weighting", "loss_weight_cell"])
config.seed = 43
config.cell_loss_type = 'cross_entropy'
config.cell_focal_gamma = 0.0
config.cell_class_weighting = 'inverse_frequency'
timed_train("Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  43%|████▎     | 43/100 [01:11<01:34,  1.65s/it, loss=9.3, score=0.537]

Stage 4 Multi Final | S4_F07_multi_ce_ablation | 1.21 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S4_F07_multi_ce_ablation',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 2,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.0,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 29,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5505449056809086,
 'epochs_ran': 44,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S4_F07_multi_ce_ablation',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.8857142857142857,
 'val_presence_macro_f1': 0.6053558844256518,
 'val_presence_weighted_f1': 0.8999697976442161,
 'val_presence_macro_precision': 0.5873015873015873,
 'val_presence_macro_recall': 0.6458333333333333,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.7357142857142858,
 'val_pose_macro_f1': 0.7173346190480813,
 'val_pose_weighted_f1': 0.7442511566580106,
 'val_pose_macro_precision': 0.7491774891774892,
 'val_pose_macro_recall': 0.701673488544354,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.2727272727272727,
 'val_cell_masked_macro_f1': 0.19673425769077946,
 'val_cell_masked_weighted_f1': 0.2668538465145843,
 'val_cell_masked_macro_precision': 0.2210989010989011,
 'val_cell_masked_macro_recall': 0.21808404667228196,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.35584669475528324,
 'val_center_m_rmse': 0.8565618855862625,
 'val_center_norm_rmse': 0.31724513844087837,
 'val_center_score': 0.6827548615591217,
 'val_center_mean_error_m': 0.7531358686574013,
 'val_center_support': 132.0,
 'val_loss_total': 7.899056870596749,
 'val_loss_presence': 0.14167082442768983,
 'val_loss_cell': 6.375203772953578,
 'val_loss_pose': 1.3567374842507498,
 'val_loss_center': 0.025445078100476946,
 'val_loss': 7.899056870596749,
 'test_presence_accuracy': 0.8992805755395683,
 'test_presence_macro_f1': 0.722,
 'test_presence_weighted_f1': 0.915251798561151,
 'test_presence_macro_precision': 0.6758771929824561,
 'test_presence_macro_recall': 0.8427350427350427,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6546762589928058,
 'test_pose_macro_f1': 0.6026663946850179,
 'test_pose_weighted_f1': 0.6532253159614257,
 'test_pose_macro_precision': 0.618325022316619,
 'test_pose_macro_recall': 0.6087587597343393,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.26153846153846155,
 'test_cell_masked_macro_f1': 0.17222812410913096,
 'test_cell_masked_weighted_f1': 0.26581108864861724,
 'test_cell_masked_macro_precision': 0.1962979242979243,
 'test_cell_masked_macro_recall': 0.1745891885891886,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.33936111147587117,
 'test_center_m_rmse': 0.8204927956240375,
 'test_center_norm_rmse': 0.3038862152366963,
 'test_center_score': 0.6961137847633037,
 'test_center_mean_error_m': 0.7209278022189147,
 'test_center_support': 130.0,
 'test_loss_total': 7.463863245874858,
 'test_loss_presence': 0.06901550225967126,
 'test_loss_cell': 5.540958560627999,
 'test_loss_pose': 1.8306967693267109,
 'test_loss_center': 0.02319238239751874,
 'test_loss': 7.463863245874858,
 'elapsed_minutes': 1.2124633550003636}

### S4_F08 - multi layer ablation

In [40]:
selected = pick_config(top_multi_configs, 0, fallback_config(profile="raw_shift", hidden_size=128, attention_dim=32, batch_size=32, learning_rate=5e-4, weight_decay=1e-4, num_layers=1, dropout=0.3, noise_sigma=0.0, bidirectional=False, cell_head_type="mlp", cell_loss_type="cross_entropy", cell_focal_gamma=0.0, cell_label_smoothing=0.0, cell_class_weighting="inverse_frequency", loss_weight_cell=2.0))
config = train_multi.TrainConfig(experiment_name="S4_F08_multi_layer_ablation")
apply_common(config, selected, ["profile", "hidden_size", "attention_dim", "batch_size", "learning_rate", "weight_decay", "num_layers", "dropout", "noise_sigma", "bidirectional", "cell_head_type", "cell_loss_type", "cell_focal_gamma", "cell_label_smoothing", "cell_class_weighting", "loss_weight_cell"])
config.seed = 43
config.num_layers = 1
config.bidirectional = False
timed_train("Stage 4 Multi Final", train_multi.train, config, use_selector=False)

Multi-output Attention-GRU:  53%|█████▎    | 53/100 [01:46<01:34,  2.01s/it, loss=9.49, score=0.531]

Stage 4 Multi Final | S4_F08_multi_layer_ablation | 1.80 min

{'phase_name': 'Multi-output Attention-GRU',
 'experiment_name': 'S4_F08_multi_layer_ablation',
 'profile': 'raw_shift',
 'hidden_size': 128,
 'attention_dim': 32,
 'dropout': 0.3,
 'batch_size': 32,
 'learning_rate': 0.0005,
 'weight_decay': 0.0001,
 'noise_sigma': 0.0,
 'num_layers': 1,
 'bidirectional': False,
 'cell_head_type': 'mlp',
 'cell_head_hidden_size': None,
 'cell_head_dropout': 0.0,
 'cell_loss_type': 'cross_entropy',
 'cell_label_smoothing': 0.0,
 'cell_focal_gamma': 0.0,
 'cell_class_weighting': 'inverse_frequency',
 'cell_class_balance_beta': 0.9999,
 'best_epoch': 39,
 'best_metric_name': 'val_composite_score',
 'best_val_composite_score': 0.5532146202008116,
 'epochs_ran': 54,
 'run_dir': 'C:\\Users\\nguyen\\Desktop\\DL_V2\\Phần 2 mô hình\\runs\\multi_output_best_model\\S4_F08_multi_layer_ablation',
 'selection': {'selected': False,
  'reason': 'selector disabled by caller',
  'source_run_dir': None,
  'selected_config': {}},
 'val_presence_accuracy': 0.8928571428571429,
 'val_presence_macro_f1': 0.6138996138996139,
 'val_presence_weighted_f1': 0.9045780474351903,
 'val_presence_macro_precision': 0.5956995760145366,
 'val_presence_macro_recall': 0.6496212121212122,
 'val_presence_support': 140.0,
 'val_pose_accuracy': 0.7214285714285714,
 'val_pose_macro_f1': 0.6870354842362956,
 'val_pose_weighted_f1': 0.7255051538499815,
 'val_pose_macro_precision': 0.6979216861569802,
 'val_pose_macro_recall': 0.6895194247911931,
 'val_pose_support': 140.0,
 'val_cell_masked_accuracy': 0.2727272727272727,
 'val_cell_masked_macro_f1': 0.23916935055135394,
 'val_cell_masked_weighted_f1': 0.272909348929954,
 'val_cell_masked_macro_precision': 0.26797478991596635,
 'val_cell_masked_macro_recall': 0.24476558735382267,
 'val_cell_masked_support': 132.0,
 'val_center_norm_mae': 0.3674599453242439,
 'val_center_m_rmse': 0.8835641191721115,
 'val_center_norm_rmse': 0.32724596788401705,
 'val_center_score': 0.672754032115983,
 'val_center_mean_error_m': 0.7756909745783314,
 'val_center_support': 132.0,
 'val_loss_total': 8.270941652570452,
 'val_loss_presence': 0.14194062929600476,
 'val_loss_cell': 6.829347120012556,
 'val_loss_pose': 1.27266628912517,
 'val_loss_center': 0.026987463874476297,
 'val_loss': 8.270941652570452,
 'test_presence_accuracy': 0.8992805755395683,
 'test_presence_macro_f1': 0.6544744318181819,
 'test_presence_weighted_f1': 0.907650016350556,
 'test_presence_macro_precision': 0.634004884004884,
 'test_presence_macro_recall': 0.6876068376068376,
 'test_presence_support': 139.0,
 'test_pose_accuracy': 0.6690647482014388,
 'test_pose_macro_f1': 0.635485073345173,
 'test_pose_weighted_f1': 0.6717803311434852,
 'test_pose_macro_precision': 0.6371636632101748,
 'test_pose_macro_recall': 0.6480826976743155,
 'test_pose_support': 139.0,
 'test_cell_masked_accuracy': 0.2076923076923077,
 'test_cell_masked_macro_f1': 0.11656095016095015,
 'test_cell_masked_weighted_f1': 0.2139711228941998,
 'test_cell_masked_macro_precision': 0.120994560994561,
 'test_cell_masked_macro_recall': 0.1270893550893551,
 'test_cell_masked_support': 130.0,
 'test_center_norm_mae': 0.3379454216131797,
 'test_center_m_rmse': 0.8264954867199701,
 'test_center_norm_rmse': 0.3061094360834275,
 'test_center_score': 0.6938905639165724,
 'test_center_mean_error_m': 0.7171251743694251,
 'test_center_support': 130.0,
 'test_loss_total': 8.154616630334647,
 'test_loss_presence': 0.1342552597931814,
 'test_loss_cell': 6.414025543404998,
 'test_loss_pose': 1.58279787293441,
 'test_loss_center': 0.023538237531408133,
 'test_loss': 8.154616630334647,
 'elapsed_minutes': 1.800092083333099}

## Final dashboard

Dashboard chỉ đọc planned `S1_/S2_/S3_/S4_` runs. Test metrics được hiển thị để báo cáo, không dùng cho selector.

In [41]:
overall = show_status()
display(overall)

summary = overall.groupby(["stage", "status"], dropna=False).size().reset_index(name="count")
display(summary)

if RUN_LOG:
    display(pd.DataFrame(RUN_LOG))

print("Expected output after Run All:")
print("- 35 planned training runs with config.json, metrics.json, history.csv, best_model.pt per completed run")
print("- Stage rankings for GRU, Attention-GRU, Multi-output, and final confirmation")
print("- Final candidates reported by validation metrics; test metrics used only for reporting")

,stage,run,experiment,profile,hidden_size,num_layers,dropout,batch_size,lr,purpose,...,bidirectional,cell_head_type,cell_loss_type,best_val_composite_score,val_cell_masked_macro_f1,test_cell_masked_macro_f1,test_pose_macro_f1,loss_weight_cell,cell_focal_gamma,cell_class_weighting
0,Stage 1 GRU,S1_G01,S1_G01_raw_h64,raw,64,1,0.0,32.0,0.001,raw baseline đối chứng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Stage 1 GRU,S1_G02,S1_G02_raw_shift_h64_anchor,raw_shift,64,1,0.0,32.0,0.001,anchor ổn định từ G02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Stage 1 GRU,S1_G03,S1_G03_raw_shift_h96,raw_shift,96,1,0.0,32.0,0.001,capacity trung bình,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Stage 1 GRU,S1_G04,S1_G04_raw_shift_h128,raw_shift,128,1,0.0,32.0,0.001,capacity cao kiểm tra overfit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Stage 1 GRU,S1_G05,S1_G05_raw_shift_h64_l2_d03,raw_shift,64,2,0.3,32.0,0.001,stacked GRU nhỏ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Stage 1 GRU,S1_G06,S1_G06_raw_shift_h96_l2_d03,raw_shift,96,2,0.3,32.0,0.001,stacked GRU trung bình,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Stage 1 GRU,S1_G07,S1_G07_raw_shift_h96_b64_lr0005,raw_shift,96,1,0.0,64.0,0.0005,batch/lr ổn định,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Stage 2 Attention,S2_A01,S2_A01_top_gru_a32,selected,selected,selected,0.2,NaN,selected,top GRU -> attention a32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Stage 2 Attention,S2_A02,S2_A02_top_gru_a48,selected,selected,selected,0.2,NaN,selected,top GRU -> attention a48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Stage 2 Attention,S2_A03,S2_A03_second_gru_a32,selected,selected,selected,0.2,NaN,selected,second GRU branch,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Stage 2 Attention,S2_A04,S2_A04_second_gru_l2_d03,selected,selected,2,0.3,NaN,selected,stacked attention branch,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Stage 2 Attention,S2_A05,S2_A05_raw_shift_h128_a32_d03,raw_shift,128,1,0.3,NaN,0.001,h128 regularized,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Stage 2 Attention,S2_A06,S2_A06_raw_shift_h96_a64_d03,raw_shift,96,1,0.3,NaN,0.001,attention width upper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Stage 2 Attention,S2_A07,S2_A07_phase_hampel_shift_h96_a32,phase_hampel_shift,96,1,0.2,NaN,0.001,denoise+shift stability,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Stage 2 Attention,S2_A08,S2_A08_phase_hampel_shift_noise_lr0005,phase_hampel_shift,96,1,0.3,NaN,0.0005,denoise+noise regularization,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Stage 2 Attention,S2_A09,S2_A09_raw_shift_bigru_h64_a32,raw_shift,64,1,0.2,NaN,0.001,BiGRU small probe,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Stage 2 Attention,S2_A10,S2_A10_raw_shift_h96_a48_lr0005,raw_shift,96,1,0.3,NaN,0.0005,A12-style regularized,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Stage 3 Multi,S3_M01,S3_M01_top_attention_linear,selected,NaN,NaN,NaN,NaN,NaN,multi baseline từ top attention,...,NaN,linear,cross_entropy,0.521066,0.207228,0.108758,0.610355,NaN,NaN,NaN
18,Stage 3 Multi,S3_M02,S3_M02_top_attention_mlp,selected,NaN,NaN,NaN,NaN,NaN,MLP cell head,...,NaN,mlp,cross_entropy,0.559524,0.167255,0.156094,0.685727,NaN,NaN,NaN
19,Stage 3 Multi,S3_M03,S3_M03_raw_shift_h128_mlp,raw_shift,NaN,NaN,NaN,NaN,NaN,raw_shift h128 MLP,...,NaN,mlp,cross_entropy,0.517677,0.111270,0.093278,0.655191,NaN,NaN,NaN
20,Stage 3 Multi,S3_M04,S3_M04_raw_shift_h128_mlp_cell2,raw_shift,NaN,NaN,NaN,NaN,NaN,cell loss x2,...,NaN,mlp,cross_entropy,0.542881,0.265881,0.122290,0.621776,2.0,NaN,NaN
21,Stage 3 Multi,S3_M05,S3_M05_raw_shift_h128_mlp_focal,raw_shift,NaN,NaN,NaN,NaN,NaN,focal cell hard examples,...,NaN,mlp,focal,0.550226,0.307528,0.106825,0.675503,2.0,2.0,NaN
22,Stage 3 Multi,S3_M06,S3_M06_raw_shift_h128_mlp_effective,raw_shift,NaN,NaN,NaN,NaN,NaN,effective-number class balance,...,NaN,mlp,focal,0.505914,0.142595,0.075839,0.617135,2.0,1.5,effective_number
23,Stage 3 Multi,S3_M07,S3_M07_phase_hampel_shift_mlp,phase_hampel_shift,NaN,NaN,NaN,NaN,NaN,denoise multi baseline,...,NaN,mlp,cross_entropy,0.537598,0.151462,0.142188,0.632846,NaN,NaN,NaN
24,Stage 3 Multi,S3_M08,S3_M08_phase_hampel_shift_mlp_noise,phase_hampel_shift,NaN,NaN,0.3,NaN,NaN,denoise+noise multi,...,NaN,mlp,cross_entropy,0.510542,0.135011,0.093252,0.596135,NaN,NaN,NaN
25,Stage 3 Multi,S3_M09,S3_M09_raw_shift_mlp_l2_d03,raw_shift,NaN,2.0,0.3,NaN,NaN,stacked multi,...,NaN,mlp,cross_entropy,0.564151,0.299880,0.145470,0.624822,NaN,NaN,NaN
26,Stage 3 Multi,S3_M10,S3_M10_raw_shift_bigru_mlp,raw_shift,64.0,NaN,NaN,NaN,NaN,BiGRU multi probe,...,True,mlp,cross_entropy,0.499223,0.178143,0.095809,0.594245,NaN,NaN,NaN
27,Stage 4 Attention Final,S4_F01,S4_F01_attention_top_seed43,selected,NaN,NaN,NaN,NaN,NaN,top attention seed check,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Stage 4 Attention Final,S4_F02,S4_F02_attention_second_seed43,selected,NaN,NaN,NaN,NaN,NaN,second attention seed check,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Stage 4 Multi Final,S4_F03,S4_F03_multi_top_seed43,selected,NaN,NaN,NaN,NaN,NaN,top multi seed 43,...,NaN,NaN,NaN,0.550545,0.196734,0.172228,NaN,NaN,NaN,NaN
30,Stage 4 Multi Final,S4_F04,S4_F04_multi_top_seed44,selected,NaN,NaN,NaN,NaN,NaN,top multi seed 44,...,NaN,NaN,NaN,0.565301,0.257170,0.118229,NaN,NaN,NaN,NaN
31,Stage 4 Multi Final,S4_F05,S4_F05_multi_second_seed43,selected,NaN,NaN,NaN,NaN,NaN,second multi seed 43,...,NaN,NaN,NaN,0.567905,0.222582,0.140255,NaN,NaN,NaN,NaN
32,Stage 4 Multi Final,S4_F06,S4_F06_multi_linear_ablation,selected,NaN,NaN,NaN,NaN,NaN,linear-vs-MLP ablation,...,NaN,NaN,NaN,0.568244,0.261109,0.206646,NaN,NaN,NaN,NaN
33,Stage 4 Multi Final,S4_F07,S4_F07_multi_ce_ablation,selected,NaN,NaN,NaN,NaN,NaN,CE-vs-focal ablation,...,NaN,NaN,NaN,0.550545,0.196734,0.172228,NaN,NaN,NaN,NaN
34,Stage 4 Multi Final,S4_F08,S4_F08_multi_layer_ablation,selected,NaN,NaN,NaN,NaN,NaN,num_layers ablation,...,NaN,NaN,NaN,0.553215,0.239169,0.116561,NaN,NaN,NaN,NaN

                     stage     status  count
0              Stage 1 GRU  completed      7
1        Stage 2 Attention  completed     10
2            Stage 3 Multi  completed     10
3  Stage 4 Attention Final  completed      2
4      Stage 4 Multi Final  completed      6

,stage,experiment_name,elapsed_minutes,run_dir
0,Stage 1 GRU,S1_G01_raw_h64,0.232400,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
1,Stage 1 GRU,S1_G02_raw_shift_h64_anchor,0.593382,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
2,Stage 1 GRU,S1_G03_raw_shift_h96,0.427393,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
3,Stage 1 GRU,S1_G04_raw_shift_h128,0.824132,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
4,Stage 1 GRU,S1_G05_raw_shift_h64_l2_d03,0.730707,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
5,Stage 1 GRU,S1_G06_raw_shift_h96_l2_d03,0.491582,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
6,Stage 1 GRU,S1_G07_raw_shift_h96_b64_lr0005,0.406869,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
7,Stage 2 Attention,S2_A01_top_gru_a32,0.577504,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
8,Stage 2 Attention,S2_A02_top_gru_a48,0.622833,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
9,Stage 2 Attention,S2_A03_second_gru_a32,0.598936,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
10,Stage 2 Attention,S2_A04_second_gru_l2_d03,0.537515,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
11,Stage 2 Attention,S2_A05_raw_shift_h128_a32_d03,0.607337,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
12,Stage 2 Attention,S2_A06_raw_shift_h96_a64_d03,0.663559,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
13,Stage 2 Attention,S2_A07_phase_hampel_shift_h96_a32,0.531154,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
14,Stage 2 Attention,S2_A08_phase_hampel_shift_noise_lr0005,2.106173,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
15,Stage 2 Attention,S2_A09_raw_shift_bigru_h64_a32,0.502108,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
16,Stage 2 Attention,S2_A10_raw_shift_h96_a48_lr0005,0.902489,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
17,Stage 3 Multi,S3_M01_top_attention_linear,0.594167,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
18,Stage 3 Multi,S3_M02_top_attention_mlp,1.536474,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
19,Stage 3 Multi,S3_M03_raw_shift_h128_mlp,0.846045,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
20,Stage 3 Multi,S3_M04_raw_shift_h128_mlp_cell2,1.370173,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
21,Stage 3 Multi,S3_M05_raw_shift_h128_mlp_focal,1.692307,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
22,Stage 3 Multi,S3_M06_raw_shift_h128_mlp_effective,0.809567,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
23,Stage 3 Multi,S3_M07_phase_hampel_shift_mlp,1.991614,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
24,Stage 3 Multi,S3_M08_phase_hampel_shift_mlp_noise,2.967598,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
25,Stage 3 Multi,S3_M09_raw_shift_mlp_l2_d03,1.970965,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
26,Stage 3 Multi,S3_M10_raw_shift_bigru_mlp,1.231874,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
27,Stage 4 Attention Final,S4_F01_attention_top_seed43,0.793482,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
28,Stage 4 Attention Final,S4_F02_attention_second_seed43,1.051672,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
29,Stage 4 Multi Final,S4_F03_multi_top_seed43,1.251148,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
30,Stage 4 Multi Final,S4_F04_multi_top_seed44,0.868981,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
31,Stage 4 Multi Final,S4_F05_multi_second_seed43,1.116575,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
32,Stage 4 Multi Final,S4_F06_multi_linear_ablation,1.480180,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
33,Stage 4 Multi Final,S4_F07_multi_ce_ablation,1.212463,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...
34,Stage 4 Multi Final,S4_F08_multi_layer_ablation,1.800092,C:\Users\nguyen\Desktop\DL_V2\Phần 2 mô hình\r...

Expected output after Run All:
- 35 planned training runs with config.json, metrics.json, history.csv, best_model.pt per completed run
- Stage rankings for GRU, Attention-GRU, Multi-output, and final confirmation
- Final candidates reported by validation metrics; test metrics used only for reporting

## Reporting-only relaxed localization metrics

These cells analyze existing multi-output `predictions.csv` files after the dashboard. They do not retrain models, do not update per-run artifacts, and do not affect validation selection.

In [43]:
def relaxed_localization_metrics(frame: pd.DataFrame) -> dict[str, float]:
    cell_labels = pd.to_numeric(frame["cell_label_human"], errors="coerce")
    cell_preds = pd.to_numeric(frame["cell_pred"], errors="coerce")
    valid = frame[cell_labels.ge(0) & cell_preds.notna()].copy()
    if valid.empty:
        return {
            "cell_masked_support": 0.0,
            "cell_masked_accuracy": 0.0,
            "cell_relaxed_soft_score": 0.0,
            "cell_within_1cell": 0.0,
            "cell_within_2cell": 0.0,
            "cell_grid_l1_mean": 0.0,
            "cell_grid_linf_mean": 0.0,
            "center_mean_error_m": 0.0,
        }
    labels = valid["cell_label_human"].astype(int)
    preds = valid["cell_pred"].astype(int)
    row_distance = (labels // 5 - preds // 5).abs()
    col_distance = (labels % 5 - preds % 5).abs()
    l1_distance = row_distance + col_distance
    linf_distance = pd.concat([row_distance, col_distance], axis=1).max(axis=1)
    exact = linf_distance.eq(0)
    orthogonal = l1_distance.eq(1)
    diagonal = row_distance.eq(1) & col_distance.eq(1)
    soft_score = exact.astype(float) + orthogonal.astype(float) * 0.4 + diagonal.astype(float) * 0.3
    center_rows = frame[pd.to_numeric(frame["presence_label"], errors="coerce").eq(1)]
    center_mean_error_m = 0.0 if center_rows.empty else float(pd.to_numeric(center_rows["center_error_m"], errors="coerce").mean())
    return {
        "cell_masked_support": float(len(valid)),
        "cell_masked_accuracy": float(exact.mean()),
        "cell_relaxed_soft_score": float(soft_score.mean()),
        "cell_within_1cell": float(linf_distance.le(1).mean()),
        "cell_within_2cell": float(linf_distance.le(2).mean()),
        "cell_grid_l1_mean": float(l1_distance.mean()),
        "cell_grid_linf_mean": float(linf_distance.mean()),
        "center_mean_error_m": center_mean_error_m,
    }

summary_rows = []
for predictions_path in sorted(MULTI_RUNS_ROOT.glob("*/predictions.csv")):
    predictions = pd.read_csv(predictions_path)
    for split, split_frame in predictions.groupby("split", sort=True):
        row = {"experiment_name": predictions_path.parent.name, "split": split}
        row.update(relaxed_localization_metrics(split_frame))
        summary_rows.append(row)

relaxed_summary = pd.DataFrame(summary_rows)
summary_path = MULTI_RUNS_ROOT / "relaxed_localization_summary.csv"
relaxed_summary.to_csv(summary_path, index=False)

if relaxed_summary.empty:
    print("No multi-output predictions.csv files found.")
else:
    ranking = relaxed_summary[relaxed_summary["split"].eq("test")].sort_values(
        ["cell_relaxed_soft_score", "cell_within_1cell", "cell_masked_accuracy"],
        ascending=[False, False, False],
    )
    display(ranking)
    display(relaxed_summary.sort_values(["experiment_name", "split"]))

print(f"Wrote reporting-only relaxed localization summary: {summary_path.name}")

,experiment_name,split,cell_masked_support,cell_masked_accuracy,cell_relaxed_soft_score,cell_within_1cell,cell_within_2cell,cell_grid_l1_mean,cell_grid_linf_mean,center_mean_error_m
26,S4_F06_multi_linear_ablation,test,130.0,0.269231,0.419231,0.669231,0.861538,1.561538,1.238462,0.724590
20,S4_F03_multi_top_seed43,test,130.0,0.261538,0.396923,0.623077,0.884615,1.592308,1.261538,0.720928
28,S4_F07_multi_ce_ablation,test,130.0,0.261538,0.396923,0.623077,0.884615,1.592308,1.261538,0.720928
24,S4_F05_multi_second_seed43,test,130.0,0.246154,0.395385,0.638462,0.876923,1.561538,1.261538,0.704989
16,S3_M09_raw_shift_mlp_l2_d03,test,130.0,0.230769,0.384615,0.638462,0.846154,1.692308,1.315385,0.697802
2,S3_M02_top_attention_mlp,test,130.0,0.238462,0.378462,0.607692,0.892308,1.646154,1.261538,0.752742
12,S3_M07_phase_hampel_shift_mlp,test,130.0,0.238462,0.374615,0.600000,0.884615,1.715385,1.323077,0.741046
30,S4_F08_multi_layer_ablation,test,130.0,0.207692,0.340769,0.561538,0.861538,1.823077,1.430769,0.717125
8,S3_M05_raw_shift_h128_mlp_focal,test,130.0,0.207692,0.326923,0.530769,0.838462,1.869231,1.469231,0.727401
6,S3_M04_raw_shift_h128_mlp_cell2,test,130.0,0.184615,0.326154,0.569231,0.869231,1.838462,1.423077,0.749302
0,S3_M01_top_attention_linear,test,130.0,0.192308,0.323846,0.546154,0.784615,1.892308,1.530769,0.740144
14,S3_M08_phase_hampel_shift_mlp_noise,test,130.0,0.153846,0.310000,0.569231,0.846154,1.846154,1.453846,0.781297
22,S4_F04_multi_top_seed44,test,130.0,0.161538,0.306923,0.546154,0.776923,1.884615,1.569231,0.739476
18,S3_M10_raw_shift_bigru_mlp,test,130.0,0.169231,0.304615,0.538462,0.784615,1.969231,1.561538,0.743067
4,S3_M03_raw_shift_h128_mlp,test,130.0,0.138462,0.265385,0.476923,0.746154,2.176923,1.723077,0.780982
10,S3_M06_raw_shift_h128_mlp_effective,test,130.0,0.130769,0.252308,0.453846,0.738462,2.246154,1.753846,0.760434

,experiment_name,split,cell_masked_support,cell_masked_accuracy,cell_relaxed_soft_score,cell_within_1cell,cell_within_2cell,cell_grid_l1_mean,cell_grid_linf_mean,center_mean_error_m
0,S3_M01_top_attention_linear,test,130.0,0.192308,0.323846,0.546154,0.784615,1.892308,1.530769,0.740144
1,S3_M01_top_attention_linear,val,132.0,0.257576,0.357576,0.522727,0.734848,2.060606,1.537879,0.798454
2,S3_M02_top_attention_mlp,test,130.0,0.238462,0.378462,0.607692,0.892308,1.646154,1.261538,0.752742
3,S3_M02_top_attention_mlp,val,132.0,0.257576,0.405303,0.651515,0.856061,1.583333,1.250000,0.787494
4,S3_M03_raw_shift_h128_mlp,test,130.0,0.138462,0.265385,0.476923,0.746154,2.176923,1.723077,0.780982
5,S3_M03_raw_shift_h128_mlp,val,132.0,0.174242,0.328030,0.590909,0.803030,1.969697,1.462121,0.811975
6,S3_M04_raw_shift_h128_mlp_cell2,test,130.0,0.184615,0.326154,0.569231,0.869231,1.838462,1.423077,0.749302
7,S3_M04_raw_shift_h128_mlp_cell2,val,132.0,0.250000,0.373485,0.583333,0.871212,1.734848,1.333333,0.759306
8,S3_M05_raw_shift_h128_mlp_focal,test,130.0,0.207692,0.326923,0.530769,0.838462,1.869231,1.469231,0.727401
9,S3_M05_raw_shift_h128_mlp_focal,val,132.0,0.318182,0.439394,0.643939,0.886364,1.553030,1.181818,0.763067
10,S3_M06_raw_shift_h128_mlp_effective,test,130.0,0.130769,0.252308,0.453846,0.738462,2.246154,1.753846,0.760434
11,S3_M06_raw_shift_h128_mlp_effective,val,132.0,0.166667,0.293939,0.515152,0.765152,2.098485,1.628788,0.807445
12,S3_M07_phase_hampel_shift_mlp,test,130.0,0.238462,0.374615,0.600000,0.884615,1.715385,1.323077,0.741046
13,S3_M07_phase_hampel_shift_mlp,val,132.0,0.272727,0.436364,0.719697,0.893939,1.530303,1.151515,0.801305
14,S3_M08_phase_hampel_shift_mlp_noise,test,130.0,0.153846,0.310000,0.569231,0.846154,1.846154,1.453846,0.781297
15,S3_M08_phase_hampel_shift_mlp_noise,val,132.0,0.204545,0.348485,0.598485,0.856061,1.803030,1.378788,0.800880
16,S3_M09_raw_shift_mlp_l2_d03,test,130.0,0.230769,0.384615,0.638462,0.846154,1.692308,1.315385,0.697802
17,S3_M09_raw_shift_mlp_l2_d03,val,132.0,0.242424,0.386364,0.621212,0.848485,1.772727,1.310606,0.771726
18,S3_M10_raw_shift_bigru_mlp,test,130.0,0.169231,0.304615,0.538462,0.784615,1.969231,1.561538,0.743067
19,S3_M10_raw_shift_bigru_mlp,val,132.0,0.234848,0.358333,0.560606,0.795455,1.840909,1.454545,0.788975
20,S4_F03_multi_top_seed43,test,130.0,0.261538,0.396923,0.623077,0.884615,1.592308,1.261538,0.720928
21,S4_F03_multi_top_seed43,val,132.0,0.272727,0.431061,0.696970,0.871212,1.522727,1.189394,0.753136
22,S4_F04_multi_top_seed44,test,130.0,0.161538,0.306923,0.546154,0.776923,1.884615,1.569231,0.739476
23,S4_F04_multi_top_seed44,val,132.0,0.287879,0.422727,0.643939,0.840909,1.590909,1.257576,0.810931
24,S4_F05_multi_second_seed43,test,130.0,0.246154,0.395385,0.638462,0.876923,1.561538,1.261538,0.704989
25,S4_F05_multi_second_seed43,val,132.0,0.250000,0.389394,0.621212,0.863636,1.712121,1.295455,0.786015
26,S4_F06_multi_linear_ablation,test,130.0,0.269231,0.419231,0.669231,0.861538,1.561538,1.238462,0.724590
27,S4_F06_multi_linear_ablation,val,132.0,0.257576,0.401515,0.636364,0.848485,1.643939,1.280303,0.766477
28,S4_F07_multi_ce_ablation,test,130.0,0.261538,0.396923,0.623077,0.884615,1.592308,1.261538,0.720928
29,S4_F07_multi_ce_ablation,val,132.0,0.272727,0.431061,0.696970,0.871212,1.522727,1.189394,0.753136
30,S4_F08_multi_layer_ablation,test,130.0,0.207692,0.340769,0.561538,0.861538,1.823077,1.430769,0.717125
31,S4_F08_multi_layer_ablation,val,132.0,0.272727,0.409848,0.636364,0.833333,1.719697,1.295455,0.775691

Wrote reporting-only relaxed localization summary: relaxed_localization_summary.csv